Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2019-03, with the labels that each got.

#402 Update StorageHelper to detect when running inside of broker and provide the correct SecretKeys
  common/src/main/java/com/microsoft/identity/common/adal/internal/cache/StorageHelper.java
Labels: bug

#397 Broker Cache Upgrade
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/migration/AdalMigrationAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/MicrosoftTokenRequest.java
Labels: enhancement

#412 Closes #411
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerApplicationMetadata.java
Labels: bug

#417 Adding temporary AndroidX Custom Tab support
  common/src/main/java/com/microsoft/identity/common/internal/ui/browser/BrowserSelector.java
Labels: platform bug

#421 Closes #389
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerTokenResponse.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/MicrosoftTokenResponse.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
Labels: Documentation, enhancement

#435 Makes ClientInfo Serializable - Resolves #1376
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectory/ClientInfo.java
Labels: bug

#438 Resolves 913-b
  common/src/androidTest/java/com/microsoft/identity/common/BrokerOAuth2TokenCacheTest.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/IBrokerApplicationMetadataCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesBrokerApplicationMetadataCache.java
Labels: bug

#440 Resolves 913-a
  common/src/androidTest/java/com/microsoft/identity/common/MicrosoftFamilyOAuth2TokenCacheTest.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MicrosoftFamilyOAuth2TokenCache.java
Labels: bug

#443 Resolves ad-accounts/#913
  common/src/androidTest/java/com/microsoft/identity/common/BrokerOAuth2TokenCacheTest.java
  common/src/androidTest/java/com/microsoft/identity/common/MicrosoftFamilyOAuth2TokenCacheTest.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/IBrokerApplicationMetadataCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MicrosoftFamilyOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesBrokerApplicationMetadataCache.java
Labels: bug
