Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2020-02, with the labels that each got.

#809 Have WebView load once per fragment lifecycle, instead of repeatedly.
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
Labels: Bug - P2, Issue Triage

#811 Fixes MSAL/#915
  common/src/main/java/com/microsoft/identity/common/internal/authorities/Authority.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/ADALOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseController.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OAuth2TokenCache.java
Labels: Bug - P1, Issue Triage

#812 Ports #811 from 1.0.14-hf2 to dev
  common/src/main/java/com/microsoft/identity/common/internal/authorities/Authority.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/ADALOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseController.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OAuth2TokenCache.java
Labels: Bug - P1, Issue Triage

#816 (dev branch) Fix for error Webview Displaying Error message (#813)
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/OAuth2WebViewClient.java
Labels: Bug - P2, Issue Triage

#819 Version number & changelog prep for 1.0.15
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/platform/Device.java
  common/versioning/version.properties
Labels: Internal, Issue Triage
