Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2021-08, with the labels that each got.

#1494 Fix Misleading Exception Message
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseController.java
Labels: No-Changelog

#1495 Updates Test to Remove No-Longer-Needed Complexity (Reflection)
  common/src/androidTest/java/com/microsoft/identity/common/adal/internal/util/HashMapExtensionTests.java
Labels: No-Changelog

#1493 Make change to accommodate WPJ migration
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidDeviceMetadata.java
  common4j/src/main/com/microsoft/identity/common/java/AuthenticationConstants.java
  common4j/src/main/com/microsoft/identity/common/java/net/HttpConstants.java
  common4j/src/main/com/microsoft/identity/common/java/platform/Device.java
  common4j/src/main/com/microsoft/identity/common/java/platform/IDeviceMetadata.java
  common4j/src/test/com/microsoft/identity/common/java/platform/DeviceTest.java
  common4j/src/test/com/microsoft/identity/common/java/platform/MockDeviceMetadata.java
Labels: No-Changelog

#1498 Revert getOS in AndroidDeviceMetadata
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidDeviceMetadata.java
Labels: No-Changelog

#1491 Fixing Perf Report Issues
  common/src/main/java/com/microsoft/identity/common/CodeMarkerManager.java
  common/src/main/java/com/microsoft/identity/common/CodeMarkerUtil.java
  uiautomationutilities/perf_tool/Program.cs
  uiautomationutilities/perf_tool/Properties/launchSettings.json
  uiautomationutilities/perf_tool/View.cs
  uiautomationutilities/perf_tool/command.cs
Labels: No-Changelog

#1501 Fix for sov cloud TSL scenarios
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/tokensharing/TokenShareUtility.java
Labels: Issue Triage, Bug - P1, Internal

#1504 Seperate OS field in Device class for eSTS and DRS request
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidDeviceMetadata.java
  common4j/src/main/com/microsoft/identity/common/java/platform/AbstractDeviceMetadata.java
  common4j/src/main/com/microsoft/identity/common/java/platform/Device.java
  common4j/src/main/com/microsoft/identity/common/java/platform/IDeviceMetadata.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequest.java
  common4j/src/test/com/microsoft/identity/common/java/platform/DeviceTest.java
  common4j/src/test/com/microsoft/identity/common/java/platform/MockDeviceMetadata.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequestTest.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsAuthorizationRequestTests.java
Labels: No-Changelog

#1508 Ports changes from #1489 (PoP + Huawei Device Compat)
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerEncryptionTests.java
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerSigningTests.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/IDevicePopManager.java
Labels: release/3.6.0

#1510 Update Common Release Version Strings & Changelog for 3.6.0
  changelog.txt
  common/versioning/version.properties
Labels: release/3.6.0

#1509 Apply (additively) changes from #1448 to increase SSOStateSerializer visibility
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/tokensharing/SSOStateSerializer.java
Labels: release/3.6.0

#1507 Brings PoP fixes from #1456 into release/3.6.0
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerEncryptionTests.java
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerSigningTests.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/Device.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/IDevicePopManager.java
Labels: release/3.6.0

#1512 [Cherry-pick] Add a method to allow for the setting of Fragment initial state on creation.
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/AuthorizationActivityFactory.java
Labels: release/3.6.0

#1505 Clear the asymmetric key if it cannot be accessed when attempting to sign ATs
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java
Labels: Internal

#1517 Apply changes from #1505 & rev to RC2
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java
  common/versioning/version.properties
Labels: release/3.6.0

#1521 Adding a constant
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/versioning/version.properties
Labels: release/3.6.0

#1462 Add vsts-release template to help modularize the code
  azure-pipelines/templates/steps/vsts-release.yml
Labels: No-Changelog

#1416 Add performance monitoring tools
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/CPUMonitor.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/DeviceMonitor.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/MemoryMonitor.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/NetworkUsageMonitor.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/PerformanceProfile.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/PerformanceProfileMonitor.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/ProcessInfo.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/performance/TrafficInfo.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/RulesHelper.java
Labels: No-Changelog

#1523 Accommodate change to DeviceStateRequest migration
  common4j/src/main/com/microsoft/identity/common/java/util/CopyUtil.java
Labels: No-Changelog

#1524 Delete get storage file name method from IMultiTypeNameValueStorage
  common/src/androidTest/java/com/microsoft/identity/common/SharedPreferencesFileManagerTests.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManager.java
  common4j/src/main/com/microsoft/identity/common/java/cache/IMultiTypeNameValueStorage.java
  common4j/src/main/com/microsoft/identity/common/java/cache/MapBackedPreferencesManager.java
Labels: No-Changelog

#1520 Fix issues with build config path
  LabApiUtilities/build.gradle
  common4j/build.gradle
Labels: No-Changelog

#1529 Wainaina/update common4j version
  common4j/versioning/version.properties
Labels: No-Changelog

#1528 Updated to merge to continuous-delivery branch
  .github/workflows/main.yml
Labels: No-Changelog

#1533 Remove iambmelt as codeowner
  CODEOWNERS
Labels: Internal, No-Changelog

#1534 Remove RC tag before release
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerSigningTests.java
  common/versioning/version.properties
Labels: Internal, release/3.6.0

#1535 Merge Release/3.6.0 to master
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerEncryptionTests.java
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerSigningTests.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/tokensharing/SSOStateSerializer.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/Device.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/IDevicePopManager.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/AuthorizationActivityFactory.java
  common/versioning/version.properties
Labels: Internal, release/3.6.0

#1531 Resolve pmd errors in common
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationSettings.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/IntuneMAMEnrollmentIdGateway.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManager.java
  common/src/main/java/com/microsoft/identity/common/internal/logging/Logger.java
  common/src/main/java/com/microsoft/identity/common/internal/request/MsalBrokerRequestAdapter.java
  common4j/src/main/com/microsoft/identity/common/java/authscheme/PopAuthenticationSchemeInternal.java
  common4j/src/main/com/microsoft/identity/common/java/constants/SpotbugsWarning.java
Labels: No-Changelog

#1537 Update changelog for 3.6.0 release & cherry-pick changes from #1513
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
Labels: Internal

#1538 Cherry-pick changes from 1521 to dev
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
Labels: No-Changelog

#1547 fix CI GitHub Action, add incrementLatestPatch and build steps
  .github/workflows/main.yml
Labels: No-Changelog

#1548 Make changes to accommondate broker4j getAccounts
  common/src/main/java/com/microsoft/identity/common/internal/migration/TokenCacheItemMigrationAdapter.java
  common/src/test/java/com/microsoft/identity/common/BrokerOAuth2TokenCacheTest.java
  common4j/src/main/com/microsoft/identity/common/java/cache/BrokerOAuth2TokenCache.java
  common4j/src/main/com/microsoft/identity/common/java/cache/IBrokerApplicationMetadataCache.java
  common4j/src/main/com/microsoft/identity/common/java/foci/FociQueryUtilities.java
  common4j/src/main/com/microsoft/identity/common/java/interfaces/IPlatformComponents.java
Labels: No-Changelog
