Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2021-06, with the labels that each got.

#1392 Add common4j spotbugs
  azure-pipelines/pull-request-validation/common4j.yml
Labels: No-Changelog

#1385 IdToken & BAM Lookup Uses Faster Cache API to Avoid Extra Decryption
  CODEOWNERS
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/MicrosoftStsAccountCredentialAdapterTest.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
Labels: Enhancement, Internal

#1403 add azure-pipelines folder
  azure-pipelines/auth-client/instrumented-test.yml
  azure-pipelines/maven-release/common.yml
  azure-pipelines/nightly-snapshot-releases/Latest Common VSTS Release.yml
  azure-pipelines/nightly-snapshot-releases/Nightly Common VSTS Release.yml
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  azure-pipelines/pull-request-validation/lab-utilities.yml
  azure-pipelines/templates/steps/auth-client/docker-tasks.yml
  azure-pipelines/templates/steps/automation-cert.yml
  azure-pipelines/templates/steps/credscan-policheck.yml
  azure-pipelines/templates/steps/maven-release/generate-release-artifacts.yml
  azure-pipelines/templates/steps/maven-release/gpg-signing.yml
  azure-pipelines/templates/steps/maven-release/upload-to-nexus-sonatype.yml
  azure-pipelines/templates/steps/nightly-snapshot-releases/common.yml
  azure-pipelines/templates/steps/spotbugs.yml
  azure-pipelines/templates/steps/ui-automation/gcloud.yml
  azure-pipelines/testapps/Android-Complete AzureSample LocalDebug.yml
  azure-pipelines/testapps/Azure Sample App PROD.yml
  azure-pipelines/vsts-releases/common.yml
Labels: No-Changelog

#1401 [PoP] Cherry-Pick Changes from #1346 to release/3.4.4
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java
  gradle/versions.gradle
Labels: release/3.4.4

#1397 [Perf] Cherry-Pick Changes from #1334 to release/3.4.4
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/cache/IAccountCredentialCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesAccountCredentialCache.java
Labels: release/3.4.4

#1398 [Perf] Cherry-Pick Changes from #1385 to release/3.4.4
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/MicrosoftStsAccountCredentialAdapterTest.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
Labels: release/3.4.4

#1400 [IcM] Cherry-Pick Changes from #1357 to release/3.4.4
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/OAuth2WebViewClient.java
Labels: release/3.4.4

#1388 Release pipelines to YAML
  azure-pipelines/maven-release/common.yml
  azure-pipelines/maven-release/common4j.yml
  azure-pipelines/templates/steps/maven-release/generate-release-artifacts.yml
  azure-pipelines/templates/steps/maven-release/gpg-signing.sh
  azure-pipelines/templates/steps/maven-release/gpg-signing.yml
  azure-pipelines/templates/steps/maven-release/maven-release-jobs.yml
  azure-pipelines/templates/steps/maven-release/upload-to-nexus-sonatype.py
  azure-pipelines/templates/steps/maven-release/upload-to-nexus-sonatype.yml
  azure-pipelines/vsts-releases/common4j.yml
Labels: No-Changelog

#1404 Fix reference to spotbugs yml file in lab utilities pipeline
  azure-pipelines/pull-request-validation/lab-utilities.yml
Labels: No-Changelog

#1405 Small changes in the YAML for instrumented test template
  azure-pipelines/templates/steps/auth-client/docker-tasks.yml
Labels: No-Changelog

#1408 Fixing testutils
  testutils/build.gradle
  testutils/src/main/java/com/microsoft/identity/internal/testutils/TestUtils.java
Labels: release/3.4.4

#1409 Update version to 3.4.4-RC1
  common/versioning/version.properties
Labels: release/3.4.4

#1412 Update Maven release Yaml
  azure-pipelines/maven-release/common.yml
  azure-pipelines/templates/steps/maven-release/generate-release-artifacts.yml
  azure-pipelines/templates/steps/maven-release/gpg-signing.sh
  azure-pipelines/templates/steps/maven-release/gpg-signing.yml
  azure-pipelines/templates/steps/maven-release/maven-release-jobs.yml
  azure-pipelines/templates/steps/maven-release/upload-to-nexus-sonatype.py
  azure-pipelines/templates/steps/maven-release/upload-to-nexus-sonatype.yml
Labels: No-Changelog

#1402 [Automation] Add helper method to get password for lab guest user
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabConstants.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabGuest.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabGuestAccountHelper.java
Labels: No-Changelog

#1415 Migrate to another package of apache http client library
  common/build.gradle
  common4j/build.gradle
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsAuthorizationRequest.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/AuthorizationRequest.java
  common4j/src/main/com/microsoft/identity/common/java/util/UrlUtil.java
  gradle/versions.gradle
Labels: No-Changelog

#1417 Pedroro/msal automation fixes
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabUserHelper.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AadLoginComponentHandler.java
Labels: No-Changelog

#1419 Small changes to Outlook sign and Teams sign in
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/OutlookApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/TeamsApp.java
Labels: No-Changelog

#1175 Perf Test C Sharp Tool
  uiautomationutilities/.gitignore
  uiautomationutilities/perf_tool/MathUtils.cs
  uiautomationutilities/perf_tool/MeasurementsConfiguration.cs
  uiautomationutilities/perf_tool/MeasurementsData.cs
  uiautomationutilities/perf_tool/MeasurementsStore.cs
  uiautomationutilities/perf_tool/Parameter.cs
  uiautomationutilities/perf_tool/PerfData.cs
  uiautomationutilities/perf_tool/PerfDataConfiguration.cs
  uiautomationutilities/perf_tool/PerfDataConfiguration.xml
  uiautomationutilities/perf_tool/PerfDataRecord.cs
  uiautomationutilities/perf_tool/PerfIdentity.csproj
  uiautomationutilities/perf_tool/PerfIdentity.sln
  uiautomationutilities/perf_tool/PerfMeasurement.cs
  uiautomationutilities/perf_tool/PerfMeasurementConfigurationsProvider.cs
  uiautomationutilities/perf_tool/PerfMeasurementsSet.cs
  uiautomationutilities/perf_tool/PerformanceMetric.cs
  uiautomationutilities/perf_tool/Program.cs
  uiautomationutilities/perf_tool/Properties/launchSettings.json
  uiautomationutilities/perf_tool/ReportHelper.cs
  uiautomationutilities/perf_tool/Task.cs
  uiautomationutilities/perf_tool/View.cs
  uiautomationutilities/perf_tool/XMLUtility.cs
  uiautomationutilities/perf_tool/changelog.txt
  uiautomationutilities/perf_tool/command.cs
  uiautomationutilities/perf_tool/readme.md
Labels: No-Changelog

#1418 Migrate to Common4j Pair
  common/src/main/java/com/microsoft/identity/common/adal/internal/tokensharing/TokenShareUtility.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/parameters/InteractiveTokenCommandParameters.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/parameters/TokenCommandParameters.java
  common/src/main/java/com/microsoft/identity/common/internal/migration/AdalMigrationAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/migration/IMigrationAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/migration/TokenCacheItemMigrationAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/migration/TokenMigrationUtility.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/request/AdalBrokerRequestAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/request/MsalBrokerRequestAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/util/QueryParamsAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/util/StringUtil.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/LastRequestTelemetry.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/AuthorizationRequest.java
  common4j/src/main/com/microsoft/identity/common/java/util/ported/Pair.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsAuthorizationRequestTests.java
  common4j/src/test/com/microsoft/identity/common/java/providers/oauth2/AuthorizationRequestTests.java
Labels: No-Changelog

#1425 Add home tenant id to Lab Account model
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/ILabAccount.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabAccount.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabClient.java
Labels: No-Changelog

#1423 Add the ability to capture http requests for verification.
  testutils/src/main/java/com/microsoft/identity/internal/testutils/HttpRequestInterceptor.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/MockHttpClient.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/shadows/ShadowHttpClient.java
Labels: No-Changelog

#1432 Rename IKeyPairStorage to INameValueStorage
  common/src/main/java/com/microsoft/identity/common/SharedPreferenceStringStorage.java
  common/src/main/java/com/microsoft/identity/common/internal/eststelemetry/EstsTelemetry.java
  common/src/main/java/com/microsoft/identity/common/internal/telemetry/AndroidTelemetryPropertiesCache.java
  common/src/main/java/com/microsoft/identity/common/internal/util/AbstractSharedPrefNameValueStorage.java
  common/src/main/java/com/microsoft/identity/common/internal/util/ClockSkewManager.java
  common/src/main/java/com/microsoft/identity/common/internal/util/SharedPrefLongNameValueStorage.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/EstsTelemetry.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/LastRequestTelemetryCache.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/SentFailedRequestsMap.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/TelemetryMap.java
  common4j/src/main/com/microsoft/identity/common/java/interfaces/INameValueStorage.java
  common4j/src/main/com/microsoft/identity/common/java/telemetry/TelemetryPropertiesCache.java
  common4j/src/main/com/microsoft/identity/common/java/util/ClockSkewManager.java
  common4j/src/test/com/microsoft/identity/common/java/InMemoryStorage.java
  common4j/src/test/com/microsoft/identity/common/java/eststelemetry/InMemorySentFailedRequestsMap.java
  common4j/src/test/com/microsoft/identity/common/java/eststelemetry/InMemoryTelemetryMap.java
Labels: No-Changelog

#1439 Avoiding an unnecessary disk-access to retrieve BrokerAppMetadata
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
Labels: Enhancement, Performance

#1441 Adding additional logging - perf recording
  common/src/main/java/com/microsoft/identity/common/internal/authorities/Authority.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectory/AzureActiveDirectory.java
Labels: Enhancement

#1444 Use mode private, fixes an issue where malformed json was coming back from the ADAL cache
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/DefaultSharedPrefsFileManagerReencrypterTest.java
  common/src/androidTest/java/com/microsoft/identity/common/SharedPreferencesFileManagerTests.java
  common/src/main/java/com/microsoft/identity/common/SharedPreferenceStringStorage.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/ADALOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/HelloCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManager.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManagerSimpleCacheImpl.java
  common/src/main/java/com/microsoft/identity/common/internal/util/ClockSkewManager.java
  common/src/test/java/com/microsoft/identity/common/BrokerOAuth2TokenCacheTest.java
  common/src/test/java/com/microsoft/identity/common/MsalOAuth2TokenCacheTest.java
  common/src/test/java/com/microsoft/identity/common/SharedPreferencesAccountCredentialCacheTest.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/TestUtils.java
Labels: Bug - P1

#1427 Avoid needless BAM lookups when the calling app is not foci
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
Labels: Enhancement, Performance

#1429 Removing low-perf fix for duplicate BAM data
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerApplicationMetadata.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesBrokerApplicationMetadataCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManagerSimpleCacheImpl.java
Labels: Enhancement, Performance
