Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2021-07, with the labels that each got.

#1449 Introduce a more human readable way to specify in tests whether password prompt is expected or not
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/PromptHandlerParameters.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/PromptParameter.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/MicrosoftStsPromptHandler.java
Labels: No-Changelog

#1448 [Major | API Breaking] SSOStateSerializer Moving Out of Internal Package
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/tokensharing/TokenShareUtility.java
  common/src/main/java/com/microsoft/identity/common/adal/tokensharing/SSOStateSerializer.java
Labels: Enhancement

#1446 Update 3.4.4-RC1 changelog to include CommandDispatcher fixes
  changelog.txt
Labels: Internal

#1391 Tests for DefaultConnectionService
  common/src/main/java/com/microsoft/identity/common/adal/internal/net/DefaultConnectionService.java
  common/src/test/java/com/microsoft/identity/common/adal/internal/PowerManagerWrapperShadow.java
  common/src/test/java/com/microsoft/identity/common/adal/internal/net/DefaultConnectionServiceTest.java
Labels: No-Changelog

#1451 Add more codeowners for common4j classes and automation
  CODEOWNERS
Labels: No-Changelog

#1458 Increment Candidate to RC2
  common/versioning/version.properties
Labels: No-Changelog

#1437 run credscan and Polichek as its own pipeline ()
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  azure-pipelines/pull-request-validation/lab-utilities.yml
  azure-pipelines/pull-request-validation/security-compliance-check-common.yml
  azure-pipelines/templates/steps/credscan-policheck.yml
  azure-pipelines/templates/steps/maven-release/maven-release-jobs.yml
  azure-pipelines/templates/steps/nightly-snapshot-releases/common.yml
  azure-pipelines/templates/steps/security-compliance-check.yml
  azure-pipelines/testapps/Android-Complete AzureSample LocalDebug.yml
  azure-pipelines/testapps/Azure Sample App PROD.yml
  azure-pipelines/vsts-releases/common.yml
  azure-pipelines/vsts-releases/common4j.yml
Labels: No-Changelog

#1407 Resurrect B2C UI Automation
  common/src/main/java/com/microsoft/identity/common/internal/authorities/AzureActiveDirectoryB2CAuthority.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
  common/src/test/java/com/microsoft/identity/common/unit/AzureActiveDirectoryB2CAuthorityTest.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/browser/BrowserChrome.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/b2c/GoogleLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/b2c/IdLabB2cSisoPolicyPromptHandler.java
Labels: No-Changelog

#1466 Remove RC label for final release
  common/versioning/version.properties
Labels: Enhancement, No-Changelog

#1467 Release/3.4.5 to master
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/BrokerOAuth2TokenCacheTest.java
  common/src/androidTest/java/com/microsoft/identity/common/CommandDispatcherTest.java
  common/src/androidTest/java/com/microsoft/identity/common/DefaultSharedPrefsFileManagerReencrypterTest.java
  common/src/androidTest/java/com/microsoft/identity/common/MsalOAuth2TokenCacheTest.java
  common/src/androidTest/java/com/microsoft/identity/common/SharedPreferencesAccountCredentialCacheTest.java
  common/src/androidTest/java/com/microsoft/identity/common/SharedPreferencesFileManagerTests.java
  common/src/main/java/com/microsoft/identity/common/exception/BaseException.java
  common/src/main/java/com/microsoft/identity/common/exception/IErrorInformation.java
  common/src/main/java/com/microsoft/identity/common/exception/TerminalException.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/ADALOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/BrokerOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/HelloCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManager.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/parameters/SilentTokenCommandParameters.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/ExceptionAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/util/ClockSkewManager.java
  common/versioning/version.properties
  testutils/src/main/java/com/microsoft/identity/internal/testutils/TestUtils.java
Labels: No-Changelog

#1468 Add a separate root project for Java only modules in common repo, basically to avoid accidentally using android build tools for building them
  azure-pipelines/pull-request-validation/common4j.yml
  azure-pipelines/pull-request-validation/lab-utilities.yml
  azure-pipelines/templates/steps/spotbugs.yml
  common-java-root/build.gradle
  common-java-root/gradle.properties
  common-java-root/gradle/wrapper/gradle-wrapper.jar
  common-java-root/gradle/wrapper/gradle-wrapper.properties
  common-java-root/gradlew
  common-java-root/gradlew.bat
  common-java-root/settings.gradle
  common/build.gradle
  common4j/versioning/version_tasks.gradle
  keyvault/build.gradle
  labapi/build.gradle
  settings.gradle
  testutils/build.gradle
  uiautomationutilities/build.gradle
  versioning/version.properties
  versioning/version_tasks.gradle
Labels: No-Changelog

#1478 [UI Automation] Add helper method to set broker flights
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/AbstractTestBroker.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerHost.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/ITestBroker.java
Labels: No-Changelog

#1454 Update getCurrentSignatureForPackage method to support tests
  common/src/main/java/com/microsoft/identity/common/internal/broker/PackageHelper.java
Labels: No-Changelog

#1455 Update perf testing documentation
  uiautomationutilities/perf_tool/PerfDataConfiguration.xml
  uiautomationutilities/perf_tool/readme.md
Labels: No-Changelog
