Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2021-02, with the labels that each got.

#1213 Log key thumbprints less often
  common/src/androidTest/java/com/microsoft/identity/common/adal/internal/cache/StorageHelperTests.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/cache/StorageHelper.java
Labels: No-Changelog

#1216 Undo constant rename as part of #1189.
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
Labels: No-Changelog

#1225 Pass requested claims to AT Deletion function when writing an AT
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java
Labels: Bug - P2, Internal, Issue Triage

#1230 Creation utility for thread pools
  common/src/main/java/com/microsoft/identity/common/internal/util/ThreadUtils.java
  common/src/test/java/com/microsoft/identity/common/unit/ThreadUtilsTests.java
Labels: No-Changelog

#1232 Fix Bug in BrokerApplicationMetadata Tracking
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/SharedPreferencesBrokerApplicationMetadataCacheTest.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesBrokerApplicationMetadataCache.java
Labels: Bug - P2, Internal, Issue Triage

#1233 Alter the test configurations to allow java8 bytecode in tests
  common/build.gradle
  gradle/versions.gradle
  testutils/build.gradle
  testutils/classes.jar
  uiautomationutilities/build.gradle
Labels: No-Changelog

#1234 Remove errant file
  testutils/classes.jar
Labels: No-Changelog

#1235 Stabilize the storage helper key change detection test
  common/src/androidTest/java/com/microsoft/identity/common/adal/internal/cache/StorageHelperTests.java
Labels: No-Changelog

#1242 Add custom test runner to accept test parameters into runner instead of supplying via BuildConfig
  uiautomationutilities/build.gradle
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/AbstractTestBroker.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/installer/AppInstallSource.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/RulesHelper.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/runner/IdentityRunnerArgs.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/runner/IdentityTestRunner.java
Labels: No-Changelog

#1243 Add StorageHelper logging change to changelog
  changelog.txt
Labels: Bug - P2, Internal, Issue Triage

#1245 Don't validate for presence of ID & RT tokens when grant type is clie…
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/TokenRequest.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/ConfidentialClientHelper.java
Labels: No-Changelog

#1244 Add support for cache reencryption
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/DefaultSharedPrefsFileManagerReencrypterTest.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/DefaultSharedPrefsFileManagerReencrypter.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/ISharedPrefsFileManagerReencrypter.java
Labels: Enhancement

#1247 Add new API to set pop attestation flags and retrieve chain
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/DevicePoPManagerTests.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidKeystoreAsymmetricRsaKey.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AsymmetricKey.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/IDevicePopManager.java
Labels: Enhancement

#1249 Expose ADAL Legacy Cache Name & Utility Method for Migration Usage in OneAuth
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationSettings.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/ADALOAuth2TokenCache.java
Labels: No-Changelog
