Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2023-05, with the labels that each got.

#2029 April UI Maintenance: Mitigate firebase apk pushing issue
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/OutlookApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/TeamsApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerApiFragment.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerHost.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/browser/BrowserEdge.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/CopyFileRule.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/RulesHelper.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/utils/AdbShellUtils.java
Labels: No-Changelog

#2031 [Pipeline] Update token for publishing test libs
  azure-pipelines/templates/steps/continuous-delivery/assemble-publish-projversion.yml
Labels: No-Changelog, Pipeline

#2033 Consolidate Storage Supplier (again)
  changelog.txt
  common/build.gradle
  common/src/androidTest/java/com/microsoft/identity/common/DefaultSharedPrefsFileManagerReencrypterTest.java
  common/src/androidTest/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyLoaderTest.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/cache/ADALOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/components/AndroidPlatformComponentsFactory.java
  common/src/main/java/com/microsoft/identity/common/components/AndroidStorageSupplier.java
  common/src/main/java/com/microsoft/identity/common/components/AndroidStorageSupplier.kt
  common/src/main/java/com/microsoft/identity/common/internal/cache/ActiveBrokerCache.kt
  common/src/main/java/com/microsoft/identity/common/internal/cache/HelloCache.java
  common/src/test/java/com/microsoft/identity/common/BrokerOAuth2TokenCacheTest.java
  common/src/test/java/com/microsoft/identity/common/MsalOAuth2TokenCacheTest.java
  common/src/test/java/com/microsoft/identity/common/SharedPreferencesAccountCredentialCacheTest.java
  common/src/test/java/com/microsoft/identity/common/SharedPreferencesAccountCredentialCacheWithMemoryCacheTest.java
  common4j/src/main/com/microsoft/identity/common/components/InMemoryStorageSupplier.java
  common4j/src/main/com/microsoft/identity/common/java/cache/BrokerOAuth2TokenCache.java
  common4j/src/main/com/microsoft/identity/common/java/cache/MapBackedPreferencesManager.java
  common4j/src/main/com/microsoft/identity/common/java/cache/MsalOAuth2TokenCache.java
  common4j/src/main/com/microsoft/identity/common/java/cache/NameValueStorageFileManagerSimpleCacheImpl.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/EstsTelemetry.java
  common4j/src/main/com/microsoft/identity/common/java/interfaces/IPlatformComponents.java
  common4j/src/main/com/microsoft/identity/common/java/interfaces/IStorageSupplier.java
  common4j/src/main/com/microsoft/identity/common/java/interfaces/IStorageSupplier.kt
  common4j/src/main/com/microsoft/identity/common/java/interfaces/PlatformComponents.java
  common4j/src/main/com/microsoft/identity/common/java/storage/StringSeparatedMultiTypeNameValueStorage.java
  common4j/src/testFixtures/java/com/microsoft/identity/common/components/InMemoryStorageSupplier.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/components/MockPlatformComponentsFactory.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/TestUtils.java
Labels: breaking-change

#2040 Change to incorporate the Java class primitives
  common/src/main/java/com/microsoft/identity/common/components/AndroidStorageSupplier.kt
Labels: No-Changelog

#2036 Add Broker Metadata Retrieval operation, Tweaks IPCStrategy
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerAccountServiceClient.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/PackageHelper.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AbstractIpcStrategyWithServiceValidation.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BoundServiceStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/ContentProviderStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/IIpcStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerMsalController.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/test/java/com/microsoft/identity/common/internal/broker/ipc/AccountManagerBoundServiceTests.java
  common/src/test/java/com/microsoft/identity/common/internal/broker/ipc/ContentProviderStrategyTests.java
  common/src/test/java/com/microsoft/identity/common/internal/ipc/IpcStrategyTests.java
Labels: No-Changelog

#2046 Add ContentProvider path
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerData.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
Labels: No-Changelog

#2048 add Utility method to remove a trailing slash
  common4j/src/main/com/microsoft/identity/common/java/util/UrlUtil.java
  common4j/src/test/com/microsoft/identity/common/java/util/UrlUtilTest.java
Labels: No-Changelog

#2034 Modify Broker Host to support e2e tests that require MWPJ enable
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/AbstractBrokerHost.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/AbstractTestBroker.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerFlightsFragment.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerHost.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/MultipleWpjApiFragment.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/SingleWpjApiFragment.java
Labels: No-Changelog

#2051 add function to get the device id using the legacy BrokerHost App
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerHost.java
Labels: No-Changelog

#2052 remove internal runblocking from queryFromBroker()
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClient.kt
Labels: No-Changelog
