Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2023-10, with the labels that each got.

#2166 Base work for the CIAM features
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/internal/commands/AcquireTokenNoFixedScopesCommand.kt
  common/src/main/java/com/microsoft/identity/common/internal/commands/BaseNativeAuthCommand.kt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseNativeAuthController.kt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/NativeAuthMsalController.kt
  common4j/build.gradle
  common4j/src/main/com/microsoft/identity/common/java/BuildValues.java
  common4j/src/main/com/microsoft/identity/common/java/authorities/Authority.java
  common4j/src/main/com/microsoft/identity/common/java/authorities/NativeAuthCIAMAuthority.kt
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/nativeauth/AcquireTokenNoFixedScopesCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/nativeauth/BaseNativeAuthCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/results/ICommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/logging/DiagnosticContext.java
  common4j/src/main/com/microsoft/identity/common/java/logging/LogSession.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/IApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/NativeAuthConstants.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/NativeAuthOAuth2Configuration.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/NativeAuthOAuth2Strategy.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/NativeAuthOAuth2StrategyFactory.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/interactors/InnerError.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/requests/NativeAuthRequest.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/responses/ApiErrorResult.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/responses/UserAttributeApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/nativeauth/responses/UserAttributeOptionsApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2StrategyParameters.java
  common4j/src/main/com/microsoft/identity/common/java/util/ApiResultUtil.kt
  common4j/src/main/com/microsoft/identity/common/java/util/CommandResultUtil.kt
  common4j/src/main/com/microsoft/identity/common/java/util/UrlUtil.java
  gradle/versions.gradle
  testutils/build.gradle
  testutils/src/main/java/com/microsoft/identity/internal/nativeauth/MockApi.kt
  testutils/src/main/java/com/microsoft/identity/internal/nativeauth/MockApiEndpoint.kt
  testutils/src/main/java/com/microsoft/identity/internal/nativeauth/MockApiResponseType.kt
  testutils/src/main/java/com/microsoft/identity/internal/nativeauth/MockApiUtils.kt
Labels: No-Changelog, Skip-Consumers-Check

#2205 Merge Oct Release v16.1.0 to dev
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check

#2181 Add passkey protocol header
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/constants/FidoConstants.kt
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2Strategy.java
Labels: Skip-Consumers-Check

#2208 v2.0 for openID
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OpenIdProviderConfigurationClient.java
Labels: Skip-Consumers-Check

#2202 Fix crash during onCreate()
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerActivity.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/InstallCertActivityLauncher.java
Labels: Skip-Consumers-Check

#2215 Update the library versions for JSON generator
  gradle/versions.gradle
Labels: No-Changelog, Skip-Consumers-Check

#2212 add removeUserLegacy method in MsalTestApp infra
  changelog.txt
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/MsalTestApp.java
Labels: Skip-Consumers-Check

#2206 [E2E Test] Fix OneAuthTestApp.handleFirstRun
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/OneAuthTestApp.java
Labels: No-Changelog

#2217 October UI Maintenance
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerAuthenticatorUpdatedVersionImpl.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/browser/BrowserEdge.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/LoadLabUserTestRule.java
Labels: No-Changelog
