Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2023-12, with the labels that each got.

#2250 Allow OneAuth to bypass redirect uri check via build config
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
  common/src/test/java/com/microsoft/identity/common/BuildConfigTest.kt
Labels: No-Changelog

#2253 Bump dependency size due to the ~500kb new NativeAuth code in common4j
  common/build.gradle
Labels: No-Changelog

#2251 Update CODEOWNERS
  CODEOWNERS
Labels: No-Changelog

#2246 Add tests for Native Auth
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/BaseNativeAuthCommand.kt
  common/src/test/java/com/microsoft/identity/common/MicrosoftStsAccountCredentialAdapterTest.java
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/ResetPasswordOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignInOAuthStrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignUpOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/scenario/ResetPasswordScenarioTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/scenario/SignUpScenarioTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/util/ArgumentCaptorUtils.kt
  common/src/test/java/com/microsoft/identity/common/java/providers/nativeauth/NativeAuthResponseHandlerTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthControllerTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/util/CommandResultUtilTest.kt
  common4j/build.gradle
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProvider.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordContinueApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordStartApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpChallengeApiResponse.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestHandlerTest.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/ApiConstants.kt
Labels: No-Changelog

#2252 Native authentication extensibility
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/INativeAuthCommandResult.kt
Labels: No-Changelog

#2259 Change function name for mock api
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/BuildValues.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Configuration.kt
Labels: No-Changelog, breaking-change, Skip-Consumers-Check

#2146 PasskeyFidoChallengeHandler and associated classes
  changelog.txt
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoChallenge.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoRequestField.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/CredManFidoManager.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/FidoChallenge.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/FidoChallengeFactory.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/FidoChallengeField.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/FidoRequestField.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/IFidoManager.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtil.kt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/test/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandlerTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/ExtendedTestWebView.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/FidoChallengeFactoryTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/FidoChallengeFieldTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/FidoChallengeTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/TestFidoManager.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtilTest.kt
  common4j/src/main/com/microsoft/identity/common/java/constants/FidoConstants.kt
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  gradle/versions.gradle
Labels: breaking-change, Skip-Consumers-Check

#2268 Changes to allow multiple app log upload
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerData.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/PackageHelper.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
Labels: No-Changelog

#2267 CredManFidoManager
  changelog.txt
  common/build.gradle
  common/consumer-rules.pro
  common/proguard-rules.pro
  common/src/main/AndroidManifest.xml
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/CredManFidoManager.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/FidoChallenge.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/FidoChallengeField.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtil.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandlerTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtilTest.kt
  common4j/src/main/com/microsoft/identity/common/java/constants/FidoConstants.kt
  gradle/versions.gradle
Labels: breaking-change, Skip-Consumers-Check
