Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2023-09, with the labels that each got.

#2164 Separate Broker API and Client SDK Active Broker caches
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClient.kt
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClientFactory.kt
  common/src/main/java/com/microsoft/identity/common/internal/cache/ClientActiveBrokerCache.kt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerMsalController.java
Labels: breaking-change, Skip-Consumers-Check

#2167 Update CopyFileRule.java with broker host apk with broker selection disabled
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/CopyFileRule.java
Labels: No-Changelog

#2175 Remove mvnAccessToken references
  azure-pipelines/code-coverage/common.yml
  azure-pipelines/continuous-delivery/common-cd.yml
  azure-pipelines/maven-release/common.yml
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/templates/steps/maven-release/maven-release-jobs.yml
  azure-pipelines/templates/steps/ui-automation/gcloud.yml
  azure-pipelines/templates/steps/vsts-release.yml
  azure-pipelines/templates/steps/vsts-release/vsts-release-template.yml
  azure-pipelines/vsts-releases/common.yml
  azure-pipelines/vsts-releases/common4j.yml
Labels: No-Changelog

#2171 Moving FidoConstants to common4j
  common4j/src/main/com/microsoft/identity/common/java/constants/FidoConstants.kt
Labels: No-Changelog

#2176 Fix spotbugs template
  azure-pipelines/templates/steps/spotbugs.yml
Labels: No-Changelog

#2178 Capture broker_operation_name on MSAL_PerformIpcStrategy span
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerOperationExecutor.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
Labels: No-Changelog

#2172 WebAuthnJsonUtil; giving default value for UserVerificationPolicy
  changelog.txt
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/internal/fido/FidoChallengeFactory.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/PublicKeyCredentialDescriptor.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/PublicKeyCredentialRequestOptions.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtil.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/FidoChallengeFactoryTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtilTest.kt
  gradle/versions.gradle
Labels: Skip-Consumers-Check

#2187 Add dependency size check task for common
  azure-pipelines/pull-request-validation/common.yml
  common/build.gradle
Labels: No-Changelog, Pipeline

#2191 Pass Lab Secret to Linux Broker Testing step in consumer pipeline
  azure-pipelines/pull-request-validation/build-consumers.yml
Labels: No-Changelog

#2184 Merge release/16.0.1 to dev
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: No-Changelog

#2188 Use ESRP to publish maven release for common and common4j
  azure-pipelines/maven-release/common.yml
  azure-pipelines/maven-release/common4j.yml
  azure-pipelines/templates/steps/maven-release/gpg-signing.sh
  azure-pipelines/templates/steps/maven-release/maven-release-jobs.yml
  common/build.gradle
  common4j/build.gradle
Labels: No-Changelog

#2186 [E2E] Handle browser first run in MsalTestApp.acquireToken
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/MsalTestApp.java
Labels: No-Changelog

#2168 Nested app auth implementation
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerRequest.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerMsalController.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
  common/src/main/java/com/microsoft/identity/common/internal/request/MsalBrokerRequestAdapter.java
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/BrokerInteractiveTokenCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/CommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ArgumentException.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/jwt/AbstractJwtRequest.java
  common4j/src/main/com/microsoft/identity/common/java/jwt/JwtRequestBody.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/AuthorizationRequest.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2Strategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/TokenRequest.java
  common4j/src/main/com/microsoft/identity/common/java/util/BrokerProtocolVersionUtil.java
Labels: Skip-Consumers-Check

#2170 Update bouncy castle version
  gradle/versions.gradle
Labels: No-Changelog

#2192 Add AzureEnvironment to ILabAccount
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/ILabAccount.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabAccount.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/constants/LabConstants.java
Labels: No-Changelog

#2194 Remove noises from storage layer
  common4j/src/main/com/microsoft/identity/common/java/crypto/StorageEncryptionManager.java
Labels: No-Changelog

#2195 Add a hub app's redirectURI to an Allowlist of valid redirectURIs
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/IAcquireMicrosoftStsTokenStrategy.java
Labels: No-Changelog
