Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-05, with the labels that each got.

#2398 Update logging of CommandParameters
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/CommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/CommandDispatcher.java
  common4j/src/main/com/microsoft/identity/common/java/logging/Logger.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/AcquireTokenNoFixedScopesCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/BaseNativeAuthCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/BaseSignInTokenCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/ResetPasswordResendCodeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/ResetPasswordStartCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/ResetPasswordSubmitCodeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/ResetPasswordSubmitNewPasswordCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignInResendCodeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignInStartCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignInSubmitCodeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignInSubmitPasswordCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignInWithContinuationTokenCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpContinueCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpResendCodeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpStartCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpSubmitCodeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpSubmitPasswordCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpSubmitUserAttributesCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/util/ILoggable.kt
Labels: No-Changelog

#2403 Fix Adfs no resource id issue in automation (CherryPick)
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AdfsLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/utils/AdbShellUtils.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/utils/UiAutomatorUtils.java
Labels: No-Changelog

#2404 Enable Cert based auth in daily and PR pipelines
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/lab-utilities.yml
  azure-pipelines/templates/steps/automation-cert.yml
Labels: No-Changelog, Skip-Consumers-Check

#2409 clean redundant verbose info
  common4j/src/main/com/microsoft/identity/common/java/cache/SharedPreferencesAccountCredentialCache.java
  common4j/src/main/com/microsoft/identity/common/java/cache/SharedPreferencesAccountCredentialCacheWithMemoryCache.java
Labels: No-Changelog

#2408 Use unauthorized client instead of invalid client
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/ResetPasswordOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignUpOAuth2StrategyTest.kt
Labels: No-Changelog, No-4j-Changelog

#2387 Extract the mock api url from code to pipeline argument
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/ResetPasswordOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignInOAuthStrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignUpOAuth2StrategyTest.kt
  common4j/build.gradle
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/BuildValues.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Configuration.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/ApiConstants.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/MockApi.kt
Labels: No-Changelog, No-4j-Changelog, Skip-Consumers-Check

#2412 Add the argument into the consumer check
  azure-pipelines/pull-request-validation/build-consumers.yml
Labels: No-Changelog, No-4j-Changelog

#2411 Logs ClientCertChallenge
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/OnDeviceCertBasedAuthChallengeHandler.java
Labels: No-Changelog

#2390 Support for multiple tokens in native auth flows
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/AcquireTokenNoFixedScopesCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/BaseNativeAuthController.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/util/CommandUtil.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
Labels: Skip-Consumers-Check

#2399 Transfer token redemption changes
  common4j/src/main/com/microsoft/identity/common/java/exception/ErrorStrings.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftTokenRequest.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/TokenRequest.java
Labels: No-Changelog

#2402 Add blockstore dependency
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
  gradle/versions.gradle
Labels: No-Changelog

#2396 Clean up native auth common logging
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/ResetPasswordResendCodeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/ResetPasswordStartCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/ResetPasswordSubmitCodeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/ResetPasswordSubmitNewPasswordCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignInResendCodeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignInStartCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignInSubmitCodeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignInSubmitPasswordCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignInWithContinuationTokenCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignUpResendCodeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignUpStartCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignUpSubmitCodeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignUpSubmitPasswordCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/BaseNativeAuthController.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/authorities/NativeAuthCIAMAuthority.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Configuration.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Strategy.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProvider.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/interactors/ResetPasswordInteractor.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/interactors/SignInInteractor.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/interactors/SignUpInteractor.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordContinueApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordPollCompletionApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordStartApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordSubmitApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInInitiateApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInTokenApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpContinueApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpStartApiResponse.kt
Labels: No-Changelog, No-4j-Changelog
