Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-03, with the labels that each got.

#2329 Flight on passkey feature (to rollback in emergencies)
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common4j/src/main/com/microsoft/identity/common/java/constants/FidoConstants.kt
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
Labels: Skip-Consumers-Check

#2334 Minor updates to passkey response logic
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtil.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/TestFidoManager.kt
  common/src/test/java/com/microsoft/identity/common/internal/fido/WebAuthnJsonUtilTest.kt
  common4j/src/main/com/microsoft/identity/common/java/constants/FidoConstants.kt
Labels: Skip-Consumers-Check

#2336 Passkey error prefix
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/constants/FidoConstants.kt
Labels: No-Changelog

#2338 Add cache for ContentProviderStrategy.isSupportedByTargetedBroker()
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClient.kt
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClientFactory.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/ContentProviderStatusLoader.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/ContentProviderStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/IContentProviderStatusLoader.kt
  common/src/main/java/com/microsoft/identity/common/sharedwithoneauth/OneAuthSharedFunctions.kt
  common/src/test/java/com/microsoft/identity/common/internal/broker/ipc/ContentProviderStatusLoaderTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/broker/ipc/ContentProviderStrategyTests.java
Labels: breaking-change, Skip-Consumers-Check

#2340 Move SHOULD_USE_ACCOUNT_MANAGER_UNTIL_EPOCH_MILLISECONDS_KEY to BaseActiveBrokerCache
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/cache/BaseActiveBrokerCache.kt
  common/src/main/java/com/microsoft/identity/common/internal/cache/ClientActiveBrokerCache.kt
  common/src/main/java/com/microsoft/identity/common/internal/cache/IActiveBrokerCache.kt
  common/src/main/java/com/microsoft/identity/common/internal/cache/IClientActiveBrokerCache.kt
  common/src/test/java/com/microsoft/identity/common/internal/activebrokerdiscovery/InMemoryActiveBrokerCache.kt
  common/src/test/java/com/microsoft/identity/common/internal/cache/ActiveBrokerCacheTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/cache/ClientActiveBrokerCacheTest.kt
Labels: breaking-change, Skip-Consumers-Check

#2356 Fixing generateSHR command controller logic
  common/src/main/java/com/microsoft/identity/common/internal/commands/GenerateShrCommand.java
Labels: No-Changelog

#2357 Add teams app SDM signout test method
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/TeamsApp.java
Labels: No-Changelog, Skip-Consumers-Check

#2360 Remove manual logging of MicrosoftStsTokenResponse
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandler.kt
Labels: No-Changelog

#2368 Refactor device code flow in broker
  common4j/src/main/com/microsoft/identity/common/java/commands/DeviceCodeFlowAuthResultCommand.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
Labels: No-Changelog
