Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-08, with the labels that each got.

#2444 Changes for restore API
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
  common/src/test/java/com/microsoft/identity/common/unit/AuthenticationConstantsTest.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog

#2464 Add Retries to Lab Api Sanity tests
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/client/LabClientTest.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/rules/RetryTestRule.java
Labels: No-Changelog

#2465 Adding OnDeviceCertBasedAuthChallengeHandler unit tests
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/OnDeviceCertBasedAuthChallengeHandler.java
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/OnDeviceCertBasedAuthChallengeHandlerTest.java
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/TestClientCertRequest.java
  common/src/test/java/com/microsoft/identity/common/shadows/ShadowKeyChain.java
Labels: No-Changelog

#2462 Authority data is persisted across different SDK instances
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/authorities/Authority.java
Labels: Skip-Consumers-Check

#2466 Spans for transfer token
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog, Skip-Consumers-Check

#2475 Fix consent page ui tests
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AadLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/MicrosoftStsPromptHandler.java
Labels: No-Changelog, Skip-Consumers-Check

#2477 Adjust JsonUtil
  common4j/src/main/com/microsoft/identity/common/java/util/JsonUtil.java
Labels: No-Changelog, Skip-Consumers-Check

#2481 Adding GeneralSecurityException block to ExceptionAdapter
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
Labels: No-Changelog

#2476 UI automation changes for transfer token restore using BrokerHost
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/MsalTestApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerApiFragment.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerHost.java
Labels: No-Changelog

#2478 Custom Response handler API in MicrosoftStsOAuth2Strategy
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/net/HttpResponse.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/AbstractMicrosoftStsTokenResponseHandler.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/ITokenResponseHandler.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2Strategy.java
  common4j/src/test/com/microsoft/identity/common/java/net/HttpResponseTests.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsOAuth2StrategyTest.java
  common4j/src/test/com/microsoft/identity/common/java/providers/oauth2/OAuth2StrategyTest.java
Labels: Skip-Consumers-Check

#2474 MFA business logic
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/GetAuthMethodsCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/MFAChallengeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/MFASubmitChallengeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/util/CommandUtil.java
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignInOAuthStrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthControllerTest.kt
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/PublicApiId.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/GetAuthMethodsCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/MFAChallengeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/MFASelectedChallengeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/MFASubmitChallengeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/INativeAuthCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/MFACommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/SignInCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Strategy.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProvider.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/interactors/SignInInteractor.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInChallengeApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInTokenApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInTokenApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/util/ListUtils.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProviderTest.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandlerTest.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/MockApiEndpoint.kt
Labels: Skip-Consumers-Check

#2469 Small logs improvements
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AccountManagerBackupIpcStrategyTargetingSpecificBrokerApp.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/IpcStrategyWithBackup.kt
Labels: No-Changelog
