Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-11, with the labels that each got.

#2530 emit power optimization status, Fixes AB#3080614
  common/src/main/java/com/microsoft/identity/common/adal/internal/PowerManagerWrapper.java
Labels: No-Changelog

#2528 Added removeBrokerAccount method to IPlatformUtil, Fixes AB#3024677
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
  common4j/src/main/com/microsoft/identity/common/java/interfaces/PlatformComponents.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
  common4j/src/testFixtures/java/com/microsoft/identity/common/components/MockPlatformComponentsFactory.java
Labels: No-Changelog

#2531 Move some test classes to test fixtures
  common4j/src/test/com/microsoft/identity/common/java/net/UrlConnectionHttpClientTest.java
  common4j/src/testFixtures/java/com/microsoft/identity/http/MockConnection.java
  common4j/src/testFixtures/java/com/microsoft/identity/http/ResponseBody.java
Labels: No-Changelog, skip AB ID validation

#2535 Rapong/release/18.1.2
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/adal/internal/PowerManagerWrapper.java
  common4j/versioning/version.properties
  versioning/version.properties
Labels: No-Changelog, skip AB ID validation

#2534 Merge amgusain/release/18.2.0 to release/18.2.0
  changelog.txt
  common/build.gradle
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2542 merge Amgusain/release/18.2.1 to release/18.2.1
  changelog.txt
  common/build.gradle
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
  common4j/src/test/com/microsoft/identity/common/java/controllers/ExceptionAdapterTests.java
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2536 merge release/18.2.0 to dev
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2516 Add Child Spans for Interactive Span
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: skip AB ID validation
