Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-02, with the labels that each got.

#2302 Changes to support app based targeting of telemetry sampling rate
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/flighting/IFlightsProvider.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/OTelUtility.java
  common4j/src/test/com/microsoft/identity/common/java/flighting/MockFlightsProvider.java
Labels: Skip-Consumers-Check

#2305 Handle Receiver Callback Exception in CommandDispatcher interactive command
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/LocalMSALController.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/activedirectoryfederationservices/ActiveDirectoryFederationServices2012R2OAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/activedirectoryfederationservices/ActiveDirectoryFederationServices2016OAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectoryb2c/AzureActiveDirectoryB2COAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/browser/BrowserAuthorizationStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/EmbeddedWebViewAuthorizationStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/CommandDispatcher.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/IAuthorizationStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2Strategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockStrategyWithMockedHttpResponse.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockTestStrategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/ResourceOwnerPasswordCredentialsTestStrategy.java
Labels: Skip-Consumers-Check

#2307 Revert changes made to method signature for futures
  common/src/main/java/com/microsoft/identity/common/internal/controllers/LocalMSALController.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/activedirectoryfederationservices/ActiveDirectoryFederationServices2012R2OAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/activedirectoryfederationservices/ActiveDirectoryFederationServices2016OAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectoryb2c/AzureActiveDirectoryB2COAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/browser/BrowserAuthorizationStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/EmbeddedWebViewAuthorizationStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/IAuthorizationStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2Strategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockStrategyWithMockedHttpResponse.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockTestStrategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/ResourceOwnerPasswordCredentialsTestStrategy.java
Labels: No-Changelog

#2310 Update version for androidxTestCoreVersion to 1.5.0
  gradle/versions.gradle
Labels: No-Changelog

#2309 Revert changes made to method signature for futures
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/LocalMSALController.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/activedirectoryfederationservices/ActiveDirectoryFederationServices2012R2OAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/activedirectoryfederationservices/ActiveDirectoryFederationServices2016OAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectoryb2c/AzureActiveDirectoryB2COAuth2Strategy.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/browser/BrowserAuthorizationStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/EmbeddedWebViewAuthorizationStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/CommandDispatcher.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/IAuthorizationStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2Strategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockStrategyWithMockedHttpResponse.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockTestStrategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/ResourceOwnerPasswordCredentialsTestStrategy.java
Labels: No-Changelog

#2320 Add wake up screen method to UiAutomatorUtils
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/utils/UiAutomatorUtils.java
Labels: No-Changelog

#2322 Remove publishing to IDDP feed
  common/build.gradle
  common4j/build.gradle
Labels: No-Changelog

#2318 Gracefully handles unexpected error in encryption layer
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/crypto/AndroidAuthSdkStorageEncryptionManager.java
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManager.java
  common/src/main/java/com/microsoft/identity/common/internal/util/AndroidKeyStoreUtil.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/StorageEncryptionManager.java
  common4j/src/main/com/microsoft/identity/common/java/storage/EncryptedNameValueStorage.java
  common4j/src/test/com/microsoft/identity/common/java/crypto/StorageEncryptionManagerTest.java
Labels: breaking-change, Skip-Consumers-Check

#2330 add back oneauth method
  common/src/main/java/com/microsoft/identity/common/internal/cache/SharedPreferencesFileManager.java
Labels: No-Changelog

#2314 CIAM custom url domains
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/authorities/Authority.java
  common4j/src/main/com/microsoft/identity/common/java/authorities/CIAMAuthority.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/OAuth2Strategy.java
  common4j/src/test/com/microsoft/identity/common/java/authorities/CIAMAuthorityTest.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/authorities/B2CTestAuthority.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/authorities/CIAMTestAuthority.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockDelayedResponseStrategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockStrategyWithMockedHttpResponse.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/MockTestStrategy.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/strategies/ResourceOwnerPasswordCredentialsTestStrategy.java
Labels: Skip-Consumers-Check

#2288 Rename "is QR + PIN available" API to "get preferred auth method".
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/CommandDispatcherTest.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/GetPreferredAuthMethodFromAuthenticator.kt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerMsalController.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/LocalMSALController.java
  common/src/main/java/com/microsoft/identity/common/internal/result/MsalBrokerResultAdapter.java
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/BaseNativeAuthController.kt
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequest.java
  common4j/src/main/com/microsoft/identity/common/java/telemetry/TelemetryEventStrings.java
  common4j/src/main/com/microsoft/identity/common/java/ui/PreferredAuthMethod.kt
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequestTest.java
Labels: Skip-Consumers-Check

#2331 Clear active broker cache if the (cached) active broker app doesn't support ipc mechanism
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClient.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AbstractIpcStrategyWithServiceValidation.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AccountManagerAddAccountStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AccountManagerBackupIpcStrategyTargetingSpecificBrokerApp.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BoundServiceStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/IIpcStrategy.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/IIpcStrategy.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/IpcStrategyWithBackup.kt
  common/src/main/java/com/microsoft/identity/common/sharedwithoneauth/OneAuthSharedFunctions.kt
  common/src/test/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClientTests.kt
  common/src/test/java/com/microsoft/identity/common/internal/broker/ipc/IpcStrategyWithBackupTests.kt
  common/src/test/java/com/microsoft/identity/common/internal/brokeroperationexecutor/BrokerOperationExecutorTests.java
  common/src/test/java/com/microsoft/identity/common/internal/cache/HelloCacheTests.java
  common/src/test/java/com/microsoft/identity/common/internal/controllers/BrokerMsalControllerTest.java
Labels: breaking-change
