Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-07, with the labels that each got.

#2433 Supporting per tenant flights
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/net/DefaultConnectionService.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/CommandDispatcher.java
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlightManager.java
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlightsManager.kt
  common4j/src/main/com/microsoft/identity/common/java/flighting/IFlightsManager.kt
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
  common4j/src/test/com/microsoft/identity/common/java/flighting/CommonFlightsManagerTest.java
  common4j/src/test/com/microsoft/identity/common/java/flighting/MockFlightsManager.java
Labels: Skip-Consumers-Check

#2442 Util method msa authority
  common/src/test/java/com/microsoft/identity/common/internal/authorities/AzureActiveDirectoryAuthorityTests.java
  common4j/src/main/com/microsoft/identity/common/java/authorities/AzureActiveDirectoryAuthority.java
Labels: No-Changelog, Skip-Consumers-Check

#2446 Update cert. (fix for MSAL and BROKER PR checks)
  azure-pipelines/templates/steps/automation-cert.yml
Labels: No-Changelog

#2440 Switching to SNI cert for new lab changes
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/KeyVaultAuthenticationClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/msal4j/Msal4jAuthClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/constants/LabConstants.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/client/LabClientTest.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilties/authentication/common/CertificateCredentialTest.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilties/authentication/common/MicrosoftClientAssertionTest.java
  azure-pipelines/templates/steps/continuous-delivery/assemble-publish-projversion.yml
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/ApiClient.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/Configuration.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/CreateTempUserApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/DeleteDeviceApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/DisablePolicyApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/EnablePolicyApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/ResetApi.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/KeyVaultAuthHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabDeviceHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabResetHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabUserHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/PolicyHelper.java
Labels: No-Changelog

#2375 Account Transfer Skips Account Chooser
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerRequest.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
  common/src/main/java/com/microsoft/identity/common/internal/request/MsalBrokerRequestAdapter.java
  common/src/test/java/com/microsoft/identity/common/internal/request/MsalBrokerRequestAdapterTests.java
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/BrokerInteractiveTokenCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/InteractiveTokenCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ErrorStrings.java
Labels: Skip-Consumers-Check

#2448 Constants for broker PR
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog

#2439 Manage test configuration through config file
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/KeyVaultCertificateBasedAuthenticationClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/constants/LabConstants.java
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  azure-pipelines/templates/steps/automation-cert.yml
  keyvault/src/main/java/com/microsoft/identity/internal/test/keyvault/ApiClient.java
  keyvault/src/main/java/com/microsoft/identity/internal/test/keyvault/Configuration.java
  testutils/build.gradle
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/ConfidentialClientHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/KeyVaultAuthHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/KeyVaultFetchHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/ConfigType.kt
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/NativeAuthCredentialHelper.kt
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/api/models/NativeAuthTestConfig.kt
Labels: No-Changelog, Skip-Consumers-Check

#2451 Added span name for refresh transfer token
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog, Skip-Consumers-Check

#2458 Disable build flag checks on Scheduled test
  common/src/test/java/com/microsoft/identity/common/BuildConfigTest.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common4j/env/BuildReason.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common4j/env/EnvironmentVariable.java
Labels: No-Changelog

#2452 July 2024 UI Fixes
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/AbstractBrokerHost.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerAuthenticatorPreviousVersionImpl.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerAuthenticatorUpdatedVersionImpl.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerCompanyPortal.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerFlightsFragment.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerHost.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerLTW.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerMicrosoftAuthenticator.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/ITestBroker.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/PromptHandlerParameters.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AadLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/IMicrosoftStsLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/MicrosoftStsPromptHandler.java
Labels: No-Changelog

#2435 Add check for unset correlation ID when configuring request headers
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/logging/DiagnosticContext.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProvider.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestHandlerTest.kt
Labels: Skip-Consumers-Check

#2456 Is LTW pre-installed constants
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog

#2461 Span Name for delete transfer token
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog, Skip-Consumers-Check

#2460 Classifying more UNKNOWN_ERRORs
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/broker/InstallCertActivityLauncher.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/AndroidAuthorizationStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/providers/RawAuthorizationResult.java
Labels: Skip-Consumers-Check
