Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-04, with the labels that each got.

#2352 Move the getActiveBroker() invocation to background thread
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/CommandDispatcherTest.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/GenerateShrCommand.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/GetCurrentAccountCommand.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/GetDeviceModeCommand.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/GetPreferredAuthMethodFromAuthenticator.kt
  common/src/main/java/com/microsoft/identity/common/internal/commands/LoadAccountCommand.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/RefreshOnCommand.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/RemoveAccountCommand.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/RemoveCurrentAccountCommand.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/LocalMSALController.java
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/BaseNativeAuthCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/test/java/com/microsoft/identity/common/internal/commands/GenerateShrCommandTest.java
  common4j/src/main/com/microsoft/identity/common/java/commands/BaseCommand.java
  common4j/src/main/com/microsoft/identity/common/java/commands/DeviceCodeFlowAuthResultCommand.java
  common4j/src/main/com/microsoft/identity/common/java/commands/DeviceCodeFlowCommand.java
  common4j/src/main/com/microsoft/identity/common/java/commands/DeviceCodeFlowTokenResultCommand.java
  common4j/src/main/com/microsoft/identity/common/java/commands/InteractiveTokenCommand.java
  common4j/src/main/com/microsoft/identity/common/java/commands/RopcTokenCommand.java
  common4j/src/main/com/microsoft/identity/common/java/commands/SilentTokenCommand.java
  common4j/src/main/com/microsoft/identity/common/java/commands/TokenCommand.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/IControllerFactory.kt
Labels: breaking-change, Skip-Consumers-Check

#2369 Return BrokerData from getFromContext if invoked from unit test
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerData.kt
Labels: No-Changelog, breaking-change, Skip-Consumers-Check

#2373 Add span BrokerAccountServiceRemoveAccount span name
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog

#2363 Add parameter to show if request is ATv2
  azure-pipelines/pull-request-validation/build-consumers.yml
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/BrokerInteractiveTokenCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ErrorStrings.java
Labels: Skip-Consumers-Check

#2376 Update flow to get token for labapi to not require automationrunner app
  LabApiUtilities/build.gradle
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabClient.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/authentication/KeyVaultAuthenticationClientTest.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClientTest.java
  azure-pipelines/continuous-delivery/common-cd.yml
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/lab-utilities.yml
  changelog.txt
Labels: Pipeline, Skip-Consumers-Check

#2381 Merge release/17.3.0
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/commands/SilentTokenCommand.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check

#2383 Update LabAuthenticationHelper to use LabAppSecret
  azure-pipelines/pull-request-validation/build-consumers.yml
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabAuthenticationHelper.java
Labels: No-Changelog

#2386 Get rid of malformed javadoc syntax errors
  common/build.gradle
  common4j/build.gradle
  common4j/src/main/com/microsoft/identity/common/java/BaseAccount.java
  common4j/src/main/com/microsoft/identity/common/java/authorities/AzureActiveDirectoryAudience.java
  common4j/src/main/com/microsoft/identity/common/java/authscheme/PopAuthenticationSchemeInternal.java
  common4j/src/main/com/microsoft/identity/common/java/cache/BrokerApplicationMetadata.java
  common4j/src/main/com/microsoft/identity/common/java/cache/BrokerOAuth2TokenCache.java
  common4j/src/main/com/microsoft/identity/common/java/cache/CacheKeyValueDelegate.java
  common4j/src/main/com/microsoft/identity/common/java/cache/IAccountCredentialCache.java
  common4j/src/main/com/microsoft/identity/common/java/cache/MsalCppOAuth2TokenCache.java
  common4j/src/main/com/microsoft/identity/common/java/cache/NameValueStorageFileManagerSimpleCacheImpl.java
  common4j/src/main/com/microsoft/identity/common/java/challengehandlers/PKeyAuthChallengeFactory.java
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/IDevicePopManager.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/SigningAlgorithm.java
  common4j/src/main/com/microsoft/identity/common/java/dto/AccessTokenRecord.java
  common4j/src/main/com/microsoft/identity/common/java/dto/AccountCredentialBase.java
  common4j/src/main/com/microsoft/identity/common/java/dto/CredentialType.java
  common4j/src/main/com/microsoft/identity/common/java/dto/IAccountRecord.java
  common4j/src/main/com/microsoft/identity/common/java/exception/BaseException.java
  common4j/src/main/com/microsoft/identity/common/java/exception/ServiceException.java
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/ResetPasswordSubmitCodeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/ResetPasswordSubmitNewPasswordCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/net/SSLSocketFactoryWrapper.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/NoopSpan.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/NoopTraceFlags.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/NoopTraceState.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/NoopTraceStateBuilder.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/OtelContextExtension.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanExtension.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftTokenErrorResponse.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftTokenResponse.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/azureactivedirectory/AzureActiveDirectoryOAuth2Strategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/IAcquireMicrosoftStsTokenStrategy.java
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/IDToken.java
  common4j/src/main/com/microsoft/identity/common/java/result/LocalAuthenticationResult.java
  common4j/src/main/com/microsoft/identity/common/java/storage/MultiTypeNameValueStorage.java
  common4j/src/main/com/microsoft/identity/common/java/telemetry/ITelemetryAccessor.java
  common4j/src/main/com/microsoft/identity/common/java/telemetry/Telemetry.java
  common4j/src/main/com/microsoft/identity/common/java/util/CommonURIBuilder.java
  common4j/src/main/com/microsoft/identity/common/java/util/IPlatformUtil.java
  common4j/src/main/com/microsoft/identity/common/java/util/JsonUtil.java
  common4j/src/main/com/microsoft/identity/common/java/util/ObjectMapper.java
  common4j/src/main/com/microsoft/identity/common/java/util/QueryParamsAdapter.java
  common4j/src/main/com/microsoft/identity/common/java/util/StringUtil.java
  common4j/src/main/com/microsoft/identity/common/java/util/ThreadUtils.java
  common4j/src/main/io/opentelemetry/api/NoopOpenTelemetry.java
  common4j/src/main/io/opentelemetry/api/metrics/NoopMeterProvider.java
  common4j/src/main/io/opentelemetry/api/trace/NoopTracerProvider.java
  common4j/src/main/io/opentelemetry/context/propagation/NoopContextPropagators.java
Labels: No-Changelog

#2382 Pipelines fixes. (Credscan suppression file, CodeQL, AndroidAuthClientVariables)
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  changelog.txt
  config/credscan/suppression.json
Labels: No-Changelog

#2391 Enable cert based auth for lab api client
  LabApiUtilities/build.gradle
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/KeyVaultAuthenticationClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClient.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClientTest.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilties/authentication/common/CertificateCredentialTest.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilties/authentication/common/MicrosoftClientAssertionTest.java
  azure-pipelines/pull-request-validation/lab-utilities.yml
  azure-pipelines/templates/steps/automation-cert.yml
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/ConfidentialClientHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/KeyVaultAuthHelper.java
Labels: No-Changelog

#2397 Remove dependency on azure-identity module
  LabApiUtilities/build.gradle
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/client/IConfidentialAuthClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/msal4j/Msal4jAuthClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/exception/LabError.java
Labels: No-Changelog
