Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-01, with the labels that each got.

#2273 Ignore NativeAuth unit tests
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/ResetPasswordOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignInOAuthStrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignUpOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/scenario/ResetPasswordScenarioTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/scenario/SignUpScenarioTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthControllerTest.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestHandlerTest.kt
Labels: No-Changelog

#2271 Correcting passkey telemetry attribute
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
Labels: No-Changelog

#2244 OneAuthTestApp automation changes
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/OneAuthTestApp.java
Labels: No-Changelog

#2262 Update logging and improve use of API response fields
  common/src/test/java/com/microsoft/identity/common/java/providers/nativeauth/NativeAuthResponseHandlerTest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordContinueApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordPollCompletionApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordStartApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordSubmitApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInInitiateApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInTokenApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpContinueApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpStartApiResponse.kt
Labels: No-Changelog

#2275 Add new scope used in CIAM tests
  testutils/src/main/java/com/microsoft/identity/internal/testutils/TestConstants.java
Labels: No-Changelog

#2219 isQrPinAvailable API
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/CommandDispatcherTest.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AbstractIpcStrategyWithServiceValidation.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
  common/src/main/java/com/microsoft/identity/common/internal/commands/IsQrPinAvailableCommand.kt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerMsalController.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/LocalMSALController.java
  common/src/main/java/com/microsoft/identity/common/internal/result/MsalBrokerResultAdapter.java
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/BaseNativeAuthController.kt
  common4j/src/main/com/microsoft/identity/common/java/controllers/BaseController.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/PublicApiId.java
  common4j/src/main/com/microsoft/identity/common/java/exception/BrokerRequiredException.kt
  common4j/src/main/com/microsoft/identity/common/java/telemetry/TelemetryEventStrings.java
Labels: Skip-Consumers-Check

#2281 Update Native Auth password reset API response
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/ResetPasswordOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/util/CommandResultUtilTest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/ResetPasswordCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordPollCompletionApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/resetpassword/ResetPasswordPollCompletionApiResult.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandlerTest.kt
Labels: Skip-Consumers-Check

#2292 update robolectricVersion
  gradle/versions.gradle
Labels: No-Changelog

#2284 Change the signature of signup/signin methods
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/SignUpStartCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/util/CommandUtil.java
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignInOAuthStrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignUpOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/scenario/SignUpScenarioTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthControllerTest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/BaseSignUpStartCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignInStartCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignInStartUsingPasswordCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpStartCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/SignUpStartUsingPasswordCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Strategy.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProvider.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/interactors/SignInInteractor.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/interactors/SignUpInteractor.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestHandlerTest.kt
Labels: Skip-Consumers-Check

#2287 Reduce calls to getInstance in Telemtry.java
  common4j/src/main/com/microsoft/identity/common/java/telemetry/Telemetry.java
Labels: No-Changelog

#2298 Remove PasswordRequired and CodeRequired results from the SignInWithContinuationTokenCommandResult
  common/src/test/java/com/microsoft/identity/common/nativeauth/util/CommandResultUtilTest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/SignInCommandResult.kt
Labels: No-Changelog, Skip-Consumers-Check

#2297 Add InvalidError for NativeAuth
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignUpOAuth2StrategyTest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/INativeAuthCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/SignUpCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/requests/resetpassword/ResetPasswordStartRequest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/requests/signin/SignInInitiateRequest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/requests/signup/SignUpStartRequest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpStartApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signup/SignUpStartApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/util/ApiErrorResponseUtil.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestHandlerTest.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandlerTest.kt
Labels: No-Changelog, Skip-Consumers-Check

#2299 Move constant in Common
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabClient.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/LoadLabUserTestRule.java
Labels: No-Changelog, Skip-Consumers-Check

#2304 Small fixes
  common/src/main/java/com/microsoft/identity/common/exception/BrokerCommunicationException.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AccountManagerBackupIpcStrategyTargetingSpecificBrokerApp.kt
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerMsalController.java
  common/src/main/java/com/microsoft/identity/common/sharedwithoneauth/OneAuthSharedFunctions.kt
  common/src/test/java/com/microsoft/identity/common/internal/broker/ipc/AccountManagerBackupIpcStrategyTargetingSpecificBrokerAppTest.kt
Labels: No-Changelog

#2306 fix unit tests (robolectric will throw an exception when context.getSystemService(Context.DEVICE_POLICY_SERVICE) is invoked)
  common/src/main/java/com/microsoft/identity/common/internal/util/AccountManagerUtil.java
Labels: No-Changelog
