Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-09, with the labels that each got.

#2491 Add PBI validation github action, Fixes AB#3024932
  .github/workflows/validate-pr-ab-id.yml
Labels: No-Changelog

#2493 MFA error handling
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
Labels: Skip-Consumers-Check

#2501 Remove triggers from pipelines and execute ABID validator on label change
  .github/workflows/validate-pr-ab-id.yml
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
Labels: No-Changelog, skip AB ID validation

#2502 Add support for testing with OneDrive, make TempUser exception handling generic, Fixes AB#2985854
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabClient.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/OneDriveApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/OutlookApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/WordApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/CopyFileRule.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/RemoveFirstPartyAppsTestRule.java
Labels: No-Changelog

#2489 Native auth MFA, AB#2083675, Fixes AB#2083675
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/GetAuthMethodsCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/MFAChallengeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/commands/MFASubmitChallengeCommand.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/util/CommandUtil.java
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignInOAuthStrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthControllerTest.kt
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
  common4j/src/main/com/microsoft/identity/common/java/eststelemetry/PublicApiId.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/GetAuthMethodsCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/MFADefaultChallengeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/MFASelectedDefaultChallengeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/MFASubmitChallengeCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/INativeAuthCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/MFACommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/SignInCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Strategy.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProvider.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandler.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/interactors/SignInInteractor.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/AuthenticationMethodApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInChallengeApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInTokenApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/SignInTokenApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/util/ListUtils.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProviderTest.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandlerTest.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/MockApiEndpoint.kt
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/ConfigType.kt
Labels: Skip-Consumers-Check

#2506 Trigger AB#ID action on synchronize, Fixes AB#3042442
  .github/workflows/validate-pr-ab-id.yml
Labels: No-Changelog

#2510 Missing exception_cause_error_locationfor NPE on ATS
  common4j/src/main/com/microsoft/identity/common/java/controllers/ExceptionAdapter.java
Labels: No-Changelog, skip AB ID validation

#2507 Automation support for Restore broker accounts in broker host, Fixes AB#2884688
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerApiFragment.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerHost.java
Labels: No-Changelog

#2511 Interrupt flow updates in broker
  common4j/src/main/com/microsoft/identity/common/java/providers/oauth2/AuthorizationRequest.java
Labels: No-Changelog, skip AB ID validation

#2503 Update device registration helper methods for test fixes with local flight for keystore keys enabled, Fixes AB#3039504
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerAuthenticatorUpdatedVersionImpl.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/device/settings/GoogleSettings.java
Labels: Test, No-Changelog

#2512 Adjustments to teams app ui handling
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/TeamsApp.java
Labels: No-Changelog, Skip-Consumers-Check, skip AB ID validation
