Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-06, with the labels that each got.

#2421 Implement new Temp User Creation and reset APIs
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabClient.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/client/LabClientTest.java
  azure-pipelines/pull-request-validation/lab-utilities.yml
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/ApiClient.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/Configuration.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/CreateTempUserApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/DeleteDeviceApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/DisablePolicyApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/EnablePolicyApi.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/api/ResetApi.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabDeviceHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabResetHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabUserHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/PolicyHelper.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/LoadLabUserTestRule.java
Labels: No-Changelog

#2426 Platform Specific Extra Query Parameters
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
  common/src/test/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtilTest.java
  common4j/src/main/com/microsoft/identity/common/java/util/IPlatformUtil.java
  common4j/src/testFixtures/java/com/microsoft/identity/common/components/MockPlatformComponentsFactory.java
Labels: Skip-Consumers-Check

#2425 Foundation of native auth E2E tests
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/ResetPasswordOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignInOAuthStrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/SignUpOAuth2StrategyTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/scenario/ResetPasswordScenarioTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/providers/microsoft/nativeauth/integration/scenario/SignUpScenarioTest.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestHandlerTest.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthResponseHandlerTest.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/ApiConstants.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/MockApi.kt
  testutils/build.gradle
  testutils/src/main/java/com/microsoft/identity/internal/testutils/TestConstants.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabConstants.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/labutils/LabUserHelper.java
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/NativeAuthCredentialHelper.kt
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/api/TemporaryEmailService.kt
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/api/models/EmailContent.kt
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/api/models/InboxContent.kt
Labels: No-Changelog

#2429 Merging alias back into dev
  azure-pipelines/pull-request-validation/build-consumers.yml
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check

#2405 Support certificate with password
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClient.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClientTest.java
  changelog.txt
Labels: Skip-Consumers-Check

#2432 Native auth gradle params
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  testutils/build.gradle
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/NativeAuthCredentialHelper.kt
Labels: No-Changelog, Skip-Consumers-Check

#2436 Bumping BouncyCastle version to 1.78
  gradle/versions.gradle
Labels: No-Changelog

#2418 Remove Storage Helper
  common/src/androidTest/java/com/microsoft/identity/common/adal/internal/cache/StorageHelperTests.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/cache/StorageHelper.java
Labels: No-Changelog

#2437 Reduce the timeout of backup IPC between broker apps
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/AccountManagerBackupIpcStrategyTargetingSpecificBrokerApp.kt
Labels: No-Changelog

#2431 Correct handling unexpected api response
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthControllerTest.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/util/CommandResultUtilTest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/INativeAuthCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/util/CommandResultUtil.kt
  testutils/build.gradle
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/NativeAuthCredentialHelper.kt
Labels: Skip-Consumers-Check

#2420 Transfer token generation changes
  common4j/src/main/com/microsoft/identity/common/java/AuthenticationConstants.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java
Labels: No-Changelog, Skip-Consumers-Check
