Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2024-10, with the labels that each got.

#2514 Add flight to preferImmediatelyAvailableCredentials
  common/src/main/java/com/microsoft/identity/common/internal/fido/CredManFidoManager.kt
Labels: No-Changelog, skip AB ID validation

#2518 Removing pipeline code that is not used anymore, Fixes AB#3059814
  azure-pipelines/maven-release/common.yml
  azure-pipelines/maven-release/common4j.yml
  azure-pipelines/templates/steps/maven-release/gpg-signing.sh
  azure-pipelines/templates/steps/maven-release/maven-release-jobs.yml
  azure-pipelines/templates/steps/maven-release/upload-to-nexus-sonatype.py
Labels: No-Changelog, Pipeline

#2513 merge Mchand/release/18.1.0 to release/18.1.0
  changelog.txt
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/internal/fido/CredManFidoManager.kt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check, skip AB ID validation

#2520 Merge release/18.1.0 to dev
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/fido/CredManFidoManager.kt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check, skip AB ID validation

#2519 Fix - [CodeQL.SM03853] Removing that accepts all certificates, Fixes AB#3064771
  keyvault/src/main/java/com/microsoft/identity/internal/test/keyvault/ApiClient.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/ApiClient.java
Labels: Test, No-Changelog

#2517 Lab consistency changes, Fixes AB#3043333
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/LabApiAuthenticationClient.java
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/client/LabClient.java
  labapi/src/main/java/com/microsoft/identity/internal/test/labapi/ApiClient.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/AzureSampleApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/OutlookApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/TeamsApp.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/app/WordApp.java
Labels: No-Changelog, Skip-Consumers-Check

#2525 Merge PRT related spans into Acquire Token spans.
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: skip AB ID validation

#2521 Clean up logs
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerActivity.java
  common4j/src/main/com/microsoft/identity/common/java/authorities/Authority.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/azureactivedirectory/AzureActiveDirectory.java
  common4j/src/main/com/microsoft/identity/common/java/result/LocalAuthenticationResult.java
  common4j/src/main/com/microsoft/identity/common/java/util/StringUtil.java
  common4j/src/main/com/microsoft/identity/common/java/util/ported/ObjectUtils.java
Labels: No-Changelog, skip AB ID validation

#2527 Check out from Robert because of github policy, Fixes AB#3037823
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/api/TemporaryEmailService.kt
Labels: No-Changelog
