Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-09, with the labels that each got.

#2750 Fix Switch browser back stack error
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/AuthorizationActivityFactory.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/BrokerAuthorizationActivity.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/SwitchBrowserActivity.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserRequestHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/switchbrowser/SwitchBrowserProtocolCoordinator.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserRequestHandlerTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/switchbrowser/SwitchBrowserProtocolCoordinatorTest.kt
Labels: skip AB ID validation

#2754 Add query parameter for Android Release OS Version, Fixes AB#3351713
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidDeviceMetadata.java
  common4j/src/main/com/microsoft/identity/common/java/platform/Device.java
  common4j/src/main/com/microsoft/identity/common/java/platform/IDeviceMetadata.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequest.java
  common4j/src/test/com/microsoft/identity/common/java/platform/MockDeviceMetadata.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequestTest.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsAuthorizationRequestTests.java
Labels: Skip-Consumers-Check

#2766 Native auth: SMS OTP MFA/JIT implementation, Fixes AB#3313635
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthMsalController.kt
  common/src/test/java/com/microsoft/identity/common/nativeauth/internal/controllers/NativeAuthControllerTest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/JITCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/controllers/results/SignInCommandResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthConstants.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/jit/JITChallengeApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/jit/JITChallengeApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/AuthenticationMethodApiResponse.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/responses/signin/AuthenticationMethodApiResult.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/util/ApiErrorResponseUtil.kt
  common4j/src/testFixtures/java/com/microsoft/identity/common/nativeauth/MockApiResponseType.kt
Labels: Skip-Consumers-Check, native-auth

#2770 Use baggage for spans, Fixes AB#3385536
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog

#2773 Update Java Script Api Exposure, Fixes AB#3385083
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/AuthUxJavaScriptInterface.kt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/OAuth2WebViewClient.java
  common/src/test/java/com/microsoft/identity/common/internal/broker/AuthUxJavaScriptInterfaceTest.kt
Labels: No-Changelog
