Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-03, with the labels that each got.

#2597 Merging alias branch into release branch (20.1.1)
  changelog.txt
  common/build.gradle
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check, skip AB ID validation

#2598 Merging March alias release back to dev
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2607 Update min SDK to 21
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/AndroidDevicePoPManagerEncryptionTests.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationSettings.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/cache/ADALOAuth2TokenCache.java
  common/src/main/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyLoader.java
  common/src/main/java/com/microsoft/identity/common/internal/fido/LegacyFidoActivityResultContract.kt
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidDevicePopManager.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidKeystoreAsymmetricRsaKey.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidSecretKeyAccessor.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AsymmetricCipher.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AsymmetricRsaKey.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/SymmetricCipher.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/CameraPermissionRequest.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/WebViewUtil.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/AbstractSmartcardCertBasedAuthChallengeHandler.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/CertBasedAuthFactory.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/DialogHolder.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/NfcSmartcardCertBasedAuthChallengeHandler.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/SmartcardPinDialog.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/UsbSmartcardCertBasedAuthChallengeHandler.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/YubiKitNfcSmartcardCertBasedAuthManager.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/certbasedauth/YubiKitUsbSmartcardCertBasedAuthManager.java
  common/src/main/java/com/microsoft/identity/common/internal/util/AccountManagerUtil.java
  common/src/test/java/com/microsoft/identity/common/adal/internal/net/DefaultConnectionServiceTest.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/IDevicePopManager.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/SigningAlgorithm.java
  gradle/versions.gradle
Labels: skip AB ID validation

#2611 Restore getAuthorizationFragmentFromStartIntentWithState
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/AuthorizationActivityFactory.kt
Labels: No-Changelog, skip AB ID validation

#2605 Added tests for intercepting cross cloud redirect url scenario , Fixes AB#3179147
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/CrossCloudChallengeHandler.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClientTest.java
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/CrossCloudChallengeHandlerTest.kt
Labels: No-Changelog

#2613 Only show QR +PIN rationale when the request origin is from Microsoft
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/CameraPermissionRequest.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/CameraPermissionRequestHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
Labels: skip AB ID validation

#2616 Improve logs and error reporting SIWG flow
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/google/GoogleSignInProvider.kt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/google/SignInWithGoogleParameters.kt
  common/src/test/java/com/microsoft/identity/common/internal/msafederation/google/GoogleSignInProviderTest.kt
Labels: skip AB ID validation
