Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-02, with the labels that each got.

#2583 Fix signInAsync method in SignInWithGoogleApi
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/IMsaFederatedCredentialCallback.kt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/google/ISignInWithGoogleCredentialCallback.kt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/google/SignInWithGoogleApi.kt
  common/src/test/java/com/microsoft/identity/common/internal/msafederation/google/MockGoogleSignInProvider.kt
  common/src/test/java/com/microsoft/identity/common/internal/msafederation/google/SignInWithGoogleApiTest.kt
Labels: skip AB ID validation

#2582 Merging Somalaya/release/19.0.1 to dev
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2585 Move generateSignatureHashes to PackageHelper
  common/src/main/java/com/microsoft/identity/common/internal/broker/PackageHelper.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/browser/AndroidBrowserSelector.java
  common/src/test/java/com/microsoft/identity/common/internal/ui/browser/AndroidBrowserSelectorTest.java
Labels: No-Changelog, skip AB ID validation

#2589 Pedroro/release/20.0.0
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2570 Native Auth E2E test generate email locally
  testutils/src/main/java/com/microsoft/identity/internal/testutils/nativeauth/api/TemporaryEmailService.kt
Labels: No-Changelog, Skip-Consumers-Check, skip AB ID validation

#2590 Adjust UI, add minimum number of retries for ui tests, Fixes AB#3139992
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/constants/LabConstants.java
  LabApiUtilities/src/test/com/microsoft/identity/labapi/utilities/client/LabClientTest.java
  uiautomationutilities/build.gradle
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/broker/BrokerMicrosoftAuthenticator.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/device/settings/GoogleSettings.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/device/settings/ISettings.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/device/settings/SamsungSettings.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/RetryTestRule.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/utils/CommonUtils.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/utils/UiAutomatorUtils.java
Labels: No-Changelog

#2594 Span changes in keypair generation, Fixes AB#3146656
  common/src/main/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyLoader.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
Labels: No-Changelog

#2596 Util method to check if sign in with google flow
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/MsaFederationExtensions.kt
Labels: No-Changelog, skip AB ID validation
