Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-07, with the labels that each got.

#2696 Changes for Only enable KDFv2 in AAD
  common4j/src/main/com/microsoft/identity/common/java/jwt/IJwtRequestSigner.java
Labels: No-Changelog, Skip-Consumers-Check, skip AB ID validation

#2701 [Cherry-pick] Changes for Only enable KDFv2 in AAD (#2696)
  common4j/src/main/com/microsoft/identity/common/java/jwt/IJwtRequestSigner.java
Labels: No-Changelog, breaking-change, skip AB ID validation

#2700 Update IP phone app teams signature constants to use SHA-512 format
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/PackageHelper.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/ProviderFactory.java
Labels: Skip-Consumers-Check, skip AB ID validation

#2666 Replace AbstractSecretKeyLoader with ISecretKeyProvider, Fixes AB#3297746
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyProviderTest.java
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationSettings.java
  common/src/main/java/com/microsoft/identity/common/crypto/AndroidAuthSdkStorageEncryptionManager.java
  common/src/main/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyProvider.java
  common/src/main/java/com/microsoft/identity/common/internal/util/AndroidKeyStoreUtil.java
  common/src/test/java/com/microsoft/identity/common/crypto/AndroidAuthSdkStorageEncryptionManagerTest.java
  common/src/test/java/com/microsoft/identity/common/shadows/ShadowAndroidSdkStorageEncryptionManager.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/StorageEncryptionManager.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/key/AES256KeyLoader.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/key/AES256SecretKeyGenerator.kt
  common4j/src/main/com/microsoft/identity/common/java/crypto/key/AbstractSecretKeyLoader.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/key/ISecretKeyGenerator.kt
  common4j/src/main/com/microsoft/identity/common/java/crypto/key/ISecretKeyProvider.kt
  common4j/src/main/com/microsoft/identity/common/java/crypto/key/KeyUtil.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/key/PredefinedKeyProvider.java
  common4j/src/test/com/microsoft/identity/common/java/crypto/KeyUtilTest.java
  common4j/src/test/com/microsoft/identity/common/java/crypto/MockAES256KeyProvider.java
  common4j/src/test/com/microsoft/identity/common/java/crypto/MockAES256KeyProviderWithGetKeyError.java
  common4j/src/test/com/microsoft/identity/common/java/crypto/StorageEncryptionManagerTest.java
  common4j/src/test/com/microsoft/identity/common/java/crypto/key/AES256SecretKeyGeneratorTest.kt
Labels: Skip-Consumers-Check

#2705 Added comment to suppress a CodeQL issue
  common/src/main/java/com/microsoft/identity/common/internal/util/AndroidKeyStoreUtil.java
Labels: No-Changelog, skip AB ID validation

#2706 Merge alias branch into release branch for 21.4.0
  changelog.txt
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/AuthUxJavaScriptInterface.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
  common/src/main/java/com/microsoft/identity/common/internal/numberMatch/NumberMatchHelper.kt
  common4j/src/main/com/microsoft/identity/common/java/jwt/IJwtRequestSigner.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check, skip AB ID validation

#2659 Improve wrapped key loader
  changelog.txt
  common/src/androidTest/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyProviderTest.java
  common/src/androidTest/java/com/microsoft/identity/common/internal/util/AndroidKeyStoreUtilTest.java
  common/src/main/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyProvider.java
  common/src/main/java/com/microsoft/identity/common/internal/util/AndroidKeyStoreUtil.java
Labels: Skip-Consumers-Check, skip AB ID validation

#2708 [Android SDK] Change Native Auth E2E tests variables, Fixes AB#3320709
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  common4j/build.gradle
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/BuildValues.java
Labels: No-Changelog, Skip-Consumers-Check, skip AB ID validation

#2709 merge release 21.4.0 to dev
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2721 Full edge to edge support
  changelog.txt
  common/build.gradle
  common/src/main/java/com/microsoft/identity/common/internal/ui/DualScreenActivity.java
  common/src/main/res/values/styles.xml
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
Labels: skip AB ID validation

#2725 set background color to 255
  common/src/main/res/values/colors.xml
  common/src/main/res/values/styles.xml
Labels: No-Changelog, skip AB ID validation
