Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-05, with the labels that each got.

#2633 Allow generating wrapping keys without PURPOSE_WRAP_KEY with Flight, Fixes AB#3260422
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/crypto/AndroidWrappedKeyLoader.java
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
Labels: Skip-Consumers-Check

#2634 Seems UI is still hopping between legacy msa ui and fluent ui, changes to support both, Fixes AB#3246594
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AadLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/utils/UiAutomatorUtils.java
Labels: No-Changelog, Skip-Consumers-Check

#2635 Cherrypick, change boolean to Boolean, Fixes AB#3261502
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
  common4j/src/main/com/microsoft/identity/common/java/platform/Device.java
  common4j/src/test/com/microsoft/identity/common/java/platform/DeviceTest.java
Labels: No-Changelog, Skip-Consumers-Check

#2636 Fadi/amwp cherrypick, Fixes AB#3261502
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
  common4j/src/main/com/microsoft/identity/common/java/platform/Device.java
  common4j/src/test/com/microsoft/identity/common/java/platform/DeviceTest.java
Labels: No-Changelog, Skip-Consumers-Check

#2642 Fix Linux consumer check in common
  azure-pipelines/pull-request-validation/build-consumers.yml
Labels: No-Changelog, skip AB ID validation

#2640 Resource Account API only, Fixes AB#3230428
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/BrokerRequest.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/ipc/BrokerOperationBundle.java
  common/src/main/java/com/microsoft/identity/common/internal/controllers/BrokerMsalController.java
  common/src/main/java/com/microsoft/identity/common/internal/request/MsalBrokerRequestAdapter.java
  common/src/main/java/com/microsoft/identity/common/internal/result/MsalBrokerResultAdapter.java
  common/src/test/java/com/microsoft/identity/common/internal/controllers/BrokerMsalControllerTest.java
  common/src/test/java/com/microsoft/identity/common/internal/request/MsalBrokerRequestAdapterTests.java
  common/src/test/java/com/microsoft/identity/common/internal/request/MsalBrokerResultAdapterTests.kt
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/BrokerResourceAccountCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/ResourceAccountCommandParameters.java
Labels: Skip-Consumers-Check

#2648 Update agent in build-consumers pipeline
  azure-pipelines/pull-request-validation/build-consumers.yml
Labels: No-Changelog, skip AB ID validation

#2647 Modify IDeviceCertificate, Fixes AB#3235066
  common4j/src/main/com/microsoft/identity/common/java/challengehandlers/IDeviceCertificate.java
  common4j/src/main/com/microsoft/identity/common/java/util/JWSBuilder.java
  common4j/src/test/com/microsoft/identity/common/java/challengehandlers/MockCertLoader.java
  common4j/src/test/com/microsoft/identity/common/java/util/JwsBuilderTest.java
Labels: No-Changelog, Skip-Consumers-Check

#2587 Gradle version change from AGP 7.4.2 to 8.1.1, Fixes AB#2779502
  LabApiUtilities/build.gradle
  azure-pipelines/pull-request-validation/build-consumers.yml
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
  azure-pipelines/pull-request-validation/lab-utilities.yml
  azure-pipelines/templates/steps/continuous-delivery/assemble-publish-projversion.yml
  azure-pipelines/templates/steps/spotbugs.yml
  changelog.txt
  common-java-root/gradle.properties
  common-java-root/gradle/wrapper/gradle-wrapper.properties
  common/build.gradle
  common4j/build.gradle
  common4j/gradle/wrapper/gradle-wrapper.properties
  gradle.properties
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.properties
  testutils/build.gradle
  testutils/src/main/AndroidManifest.xml
  uiautomationutilities/build.gradle
  uiautomationutilities/src/main/AndroidManifest.xml
Labels: Skip-Consumers-Check

#2653 Update Json Schema, put JavaScript API behind a flight, Fixes AB#3203956, Closed AB#3203956
  common/src/main/java/com/microsoft/identity/common/internal/broker/AuthUxJavaScriptInterface.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/AuthUxJsonPayload.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/test/java/com/microsoft/identity/common/internal/broker/AuthUxJavaScriptInterfaceTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/broker/AuthUxJsonPayloadTest.kt
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
Labels: No-Changelog
