Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-06, with the labels that each got.

#2662 Catch exceptions on get hinge
  common/src/main/java/com/microsoft/identity/common/internal/ui/DualScreenActivity.java
Labels: No-Changelog, skip AB ID validation

#2664 cherrypick numberMatch
  common/src/main/java/com/microsoft/identity/common/internal/broker/AuthUxJavaScriptInterface.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/test/java/com/microsoft/identity/common/internal/broker/AuthUxJavaScriptInterfaceTest.kt
Labels: No-Changelog

#2658 Add capabilities parameter to the flow start operations, Fixes AB#3288182, Closed AB#3288182
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/commands/parameters/BaseNativeAuthCommandParameters.java
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthOAuth2Configuration.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProvider.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/requests/resetpassword/ResetPasswordStartRequest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/requests/signin/SignInInitiateRequest.kt
  common4j/src/main/com/microsoft/identity/common/java/nativeauth/providers/requests/signup/SignUpStartRequest.kt
  common4j/src/test/com/microsoft/identity/common/java/nativeauth/providers/NativeAuthRequestProviderTest.kt
Labels: No-Changelog, No-4j-Changelog

#2667 changes accommodating the WrappedKeyAlgoIdentifier module, Fixes AB#3297251
  changelog.txt
  common4j/src/main/com/microsoft/identity/common/java/exception/ClientException.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog

#2670 Merge release/21.2.0
  common4j/versioning/version.properties
  versioning/version.properties
Labels: No-Changelog, skip AB ID validation

#2676 Remove unused crypto files tagged by CodeQL, Fixes AB#3301719
  LabApiUtilities/src/main/com/microsoft/identity/labapi/utilities/authentication/common/MicrosoftClientAssertion.java
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/AndroidKeyStoreAccessorTests.java
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/RawKeyAccessorTest.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidKeyStoreAccessor.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidSecretKeyAccessor.java
  common4j/src/main/com/microsoft/identity/common/java/crypto/RawKeyAccessor.java
Labels: No-Changelog

#2675 Merge release/21.3.0
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2681 June 2025 Ui Automation Updates, Fixes AB#3304003
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/IOAuth2LoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/b2c/B2CIdLabLocalLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/b2c/FacebookLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/b2c/GoogleLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/b2c/IdLabB2cSisoPolicyPromptHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AadLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AdfsLoginComponentHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/MicrosoftStsPromptHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/TlsPromptHandler.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/PowerLiftIncidentRule.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/RetryTestRule.java
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/rules/RulesHelper.java
Labels: No-Changelog, Skip-Consumers-Check

#2673 Showing webcp flow in webview , Fixes AB#3135912
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/ReAttachPrtHeaderHandler.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClientTest.java
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/ReAttachPrtHeaderHandlerTest.kt
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: Skip-Consumers-Check

#2685 adjust MSA handling to handle fluent ui as well, Fixes AB#3304003
  uiautomationutilities/src/main/java/com/microsoft/identity/client/ui/automation/interaction/microsoftsts/AadLoginComponentHandler.java
Labels: No-Changelog, Skip-Consumers-Check

#2689 Fix playstore url launch for broker apps, Fixes AB#3307594
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClientTest.java
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
Labels: No-Changelog, Skip-Consumers-Check

#2690 Edge to edge fix limited to brokered only scenarios, Fixes AB#3293334
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
Labels: No-Changelog, Skip-Consumers-Check

#2691 Updating handling of ssl error received in Android WebView's onReceivedSslError callback, Fixes AB#3268908
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/OAuth2WebViewClient.java
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClientTest.java
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
Labels: Skip-Consumers-Check
