Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-04, with the labels that each got.

#2620 remove config from AndroidDevicePoPManagerEncryptionTests
  common/src/androidTest/java/com/microsoft/identity/common/internal/platform/AndroidDevicePoPManagerEncryptionTests.java
Labels: No-Changelog, skip AB ID validation

#2623 Merging April release Working/release/21.0.0 to dev
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2612 Add telemetry for the switch browser protocol
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserRequestHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/switchbrowser/SwitchBrowserProtocolCoordinator.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserRequestHandlerTest.kt
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/AttributeName.java
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: skip AB ID validation

#2625 Revert #2618
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/BrokerDiscoveryClientFactory.kt
  common/src/main/java/com/microsoft/identity/common/internal/activebrokerdiscovery/LegacyBrokerDiscoveryClient.kt
Labels: skip AB ID validation

#2627 Pass Work Profile existence, OS Version, and Manufacturer to ESTS, Fixes AB#3138815
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/components/AndroidPlatformComponentsFactory.java
  common/src/main/java/com/microsoft/identity/common/internal/util/WorkProfileUtil.java
  common4j/src/main/com/microsoft/identity/common/java/platform/Device.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequest.java
  common4j/src/test/com/microsoft/identity/common/java/platform/DeviceTest.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequestTest.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsAuthorizationRequestTests.java
Labels: Skip-Consumers-Check

#2629 Prevents triggering on commits to target branch
  azure-pipelines/pull-request-validation/common.yml
  azure-pipelines/pull-request-validation/common4j.yml
Labels: No-Changelog, Skip-Consumers-Check, skip AB ID validation

#2630 Move camera logic to CameraPermissionRequestHandler and add SdmQrPinManager , Fixes AB#3121976
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/broker/IRestrictionsManager.kt
  common/src/main/java/com/microsoft/identity/common/internal/broker/SdmQrPinManager.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/CameraPermissionRequestHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
Labels: Skip-Consumers-Check

#2631 DUNA. Prevent phish attack in “switch_browser” flow. , Fixes AB#3250169
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java
  common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserChallenge.kt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserRequestHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/switchbrowser/SwitchBrowserProtocolCoordinator.kt
  common/src/main/java/com/microsoft/identity/common/internal/ui/webview/switchbrowser/SwitchBrowserUriHelper.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserRequestHandlerTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/SwitchBrowserUriHelperTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/switchbrowser/SwitchBrowserProtocolCoordinatorTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/ui/webview/switchbrowser/SwitchBrowserUriHelperTest.kt
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
Labels: Skip-Consumers-Check

#2632 Add flight to control AM API WorkProfile, Fixes AB#3138815
  common/src/main/java/com/microsoft/identity/common/components/AndroidPlatformComponentsFactory.java
  common/src/main/java/com/microsoft/identity/common/internal/util/WorkProfileUtil.java
  common4j/src/main/com/microsoft/identity/common/java/flighting/CommonFlight.java
  common4j/src/main/com/microsoft/identity/common/java/platform/Device.java
  common4j/src/main/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequest.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/MicrosoftAuthorizationRequestTest.java
  common4j/src/test/com/microsoft/identity/common/java/providers/microsoft/microsoftsts/MicrosoftStsAuthorizationRequestTests.java
Labels: No-Changelog, Skip-Consumers-Check
