Repository AzureAD/microsoft-authentication-library-common-for-android, pull requests merged in 2025-01, with the labels that each got.

#2561 Managed profile Android util method
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/fido/AuthFidoChallengeHandler.kt
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java
Labels: skip AB ID validation

#2563 Merge Amgusain/release/18.2.3 to release/18.2.3
  changelog.txt
  common/build.gradle
  common/src/androidTest/java/com/microsoft/identity/common/internal/broker/SDMBroadcastReceiverTests.java
  common/src/main/java/com/microsoft/identity/common/internal/broker/SDMBroadcastReceiver.java
  common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidBroadcaster.java
  common4j/src/main/com/microsoft/identity/common/java/constants/SharedDeviceModeConstants.kt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: skip AB ID validation

#2566 Alias to Dev January 2025
  changelog.txt
  common4j/versioning/version.properties
  versioning/version.properties
Labels: Skip-Consumers-Check, skip AB ID validation

#2574 Span name added for corruption exception, Fixed AB#3131729
  common4j/src/main/com/microsoft/identity/common/java/opentelemetry/SpanName.java
Labels: No-Changelog

#2580 On getBrowserSafeList return empty list if null
  common4j/src/main/com/microsoft/identity/common/java/commands/parameters/InteractiveTokenCommandParameters.java
Labels: No-Changelog, skip AB ID validation

#2581 Add server client id to SignInWithGoogleParameters
  changelog.txt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/MsaFederatedSignInProviderFactory.kt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/MsaFederationConstants.kt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/google/GoogleSignInProvider.kt
  common/src/main/java/com/microsoft/identity/common/internal/msafederation/google/SignInWithGoogleParameters.kt
  common/src/test/java/com/microsoft/identity/common/internal/msafederation/google/GoogleSignInProviderTest.kt
  common/src/test/java/com/microsoft/identity/common/internal/msafederation/google/SignInWithGoogleParametersTest.kt
Labels: skip AB ID validation
